### ISSUE TITLE
Structure view for delegate member is printed incorrectly

### ISSUE THREAD

**Issue by rikkimax** [intellij-dlanguage/intellij-dlanguage#1024]
**Desktop (please provide environment info):**
 - OS: Windows 10
 - IDE: Intellij 2024.2.2
 - Plugin Version 1.35

**Describe the problem**

No space is added for the return type of a delegate when printed in the structure view.

**Please provide full details to reproduce the problem**

**Screenshots**
![Capture](https://github.com/user-attachments/assets/336801e0-45ad-4370-926a-683b2e47850f)

**Comment by SingingBush** [comment]
looks like it probably just needs the x3 lines in [DStructureViewElement.kt](https://github.com/intellij-dlanguage/intellij-dlanguage/blob/develop/src/main/kotlin/io/github/intellij/dlanguage/structure/DStructureViewElement.kt) changing from 

```
append(" : ${element.basicType?.text}${element.typeSuffixes.joinToString(""){ it.text }}")
```

to

```
append(" : ${element.basicType?.text} ${element.typeSuffixes.joinToString(" "){ it.text }}".trim())
```

There's no test for this file so it's worth getting some tests in place as well

**Comment by SingingBush** [comment]
fix in place for the next release with test coverage
