### ISSUE TITLE
Add Support for 2024.3

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#1027]
```
Plugin 'D Language' (version '1.35') is not compatible with the current version of the IDE, because it requires build 242.* or older but the current build is IU-243.21565.193
```

the time has come to increase the untilBuild version to `243.*`

**Comment by SingingBush** [comment]
seems that _isOpenProjectSettingsAfter()_ no longer exists on ProjectImportBuilder

```
    override fun isOpenProjectSettingsAfter(): Boolean {
        return getParameters().openModuleSettings
    }
```
https://github.com/intellij-dlanguage/intellij-dlanguage/blob/fb9872d3ff83da9e91e5d0dde040364fbf78f48f/dub/src/main/kotlin/io/github/intellij/dub/project/DubProjectImportBuilder.kt#L57C1-L59C6

```
e: file:///home/runner/work/intellij-dlanguage/intellij-dlanguage/dub/src/main/kotlin/io/github/intellij/dub/project/DubProjectImportBuilder.kt:57:5 'isOpenProjectSettingsAfter' overrides nothing
```

**Comment by Bizarrus** [comment]
I've installed since 1hr on **CLion** `2024.2.3` and it works (mostly) without problems.

**Comment by SingingBush** [comment]
pushed the fix now and doing a release
