### ISSUE TITLE
Does not error on undefined symbols.

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#104]
`class Foo {`
`void bar() {`
`//do something`
`}`
`}`

`Foo foo = new Foo();`
`foo.foo();//The plugin does not detect that foo.foo does not exist, and does not underline/mark appropriately.`

**Comment by mbierlee** [comment]
Does pull request #212 fix this issue?

**Comment by pirocks** [comment]
Sorta. When I was making this issue I was thinking of an in ide solution, instead of relying on the compiler.

**Comment by pirocks** [comment]
PR #216, adds an in ide solution.
