### ISSUE TITLE
Add debugging support

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#106]
Title pretty much explains everything. The golang plugin for intellij supports debugging and could be used as reference.
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/commit/3a21e14a9807f6c51ee5bca308a50f15eaa01e9d

**Comment by kingsleyh** [comment]
I've been avoiding a debugger for a long time - because in D all the debuggers seem to be quite poor. I'm not sure which one would work cross platform

Also my priority was to get all the language based features working

**Comment by pirocks** [comment]
Most other D IDEs tend to use gdb. I was creating this issue more for the future than for now.

**Comment by rikkimax** [comment]
Mago supports a GDB interface https://github.com/rainers/mago so Windows
will be fairly easy implement once Linux is done.

**Comment by pirocks** [comment]
Mago support currently waiting on https://github.com/rainers/mago/issues/14. I may work around the issue.

**Comment by pirocks** [comment]
Also waiting on https://github.com/rainers/mago/issues/15

**Comment by pirocks** [comment]
I'm looking into using lldbmi instead of mafo-mi, becuase of far better support/project resources.

**Comment by andre2007** [comment]
Mago-Mi is almost working with https://github.com/intellij-dlanguage/intellij-dlanguage/pull/429 and recent Mago-Mi. See pull request for more info
