### ISSUE TITLE
Incorrect syntax error with enums

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#110]
The following is highlighted with a syntax error on the first `{` in the enum
`module enumtest;`
`unittest`
`{`
`enum E {a,b};`
`}`

**Comment by kingsleyh** [comment]
This looks like a problem in the bnf grammar related to the enum rules when inside the some of the scopes - I noticed its fine when inside a class or a out on its own. I think it’s something to do with the BlockStatement rules in combination with the Enum rules. Probably going to be tricky to track down - as from experience fixing one thing can lead to breaking several others. Which makes the tests in the area super important.

**Comment by pirocks** [comment]
I think I have determined the cause of this problem. 
When the parser sees the enum keyword it expects this:
`enum int someConstant = 0;`
instead of 
`enum AnEnum{`
`member1,etc`
`}`

**Comment by pirocks** [comment]
This has since been fixed.
