### ISSUE TITLE
Bring documentation into master from gh-pages?

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#118]
GitHub pages have now changed so you can nominate a directory in the master branch as the location of the pages to render. This makes the gh-pages branch redundant. I believe the new way much better for projects and for actually getting website changes done.

**Comment by russel** [comment]
I am just wondering if the gh-pages branch is currently used, dlanguage.github.io is a 404.

**Comment by SingingBush** [comment]
I don't think the gh-pages is used but I think it would be worth giving it a massive overhaul.

http://intellij-dlanguage.github.io/intellij-dlanguage/

It's very out of date

Is this something you want to pickup?

**Comment by russel** [comment]
I can certainly do something with this. Step 1 for me is to ditch the gh-pages branch and put the stuff into master/develop in the /docs directory or have a separate repository. It may be just me but I don't find the separate branch approach at all workable.

**Comment by SingingBush** [comment]
I've created https://github.com/intellij-dlanguage/intellij-dlanguage.github.io and moved the old gh-pages stuff into there. From now on we can maintain it there. I'll delete the gh-pages branch.

new site url is simply https://intellij-dlanguage.github.io/ as it for the organisation as a whole it can include documentation for any other related projects we have
