### ISSUE TITLE
The documentation on the frontpage of the repository isn't up to date.

### ISSUE THREAD

**Issue by SjoerdNijboer** [intellij-dlanguage/intellij-dlanguage#120]
The documentation on how to start isn't entirely accurate.
Screens have changed, names on buttons have changed causing some confusion.
I can't follow the steps and get a working compile of Hello World.
(Windows with dmd.)

If it is up to date then it's not clear for a goof like me. :P

**Comment by kingsleyh** [comment]
Ok thanks for pointing that out - I will add a simple getting started tutorial that is more clear. What is currently not working for you?

**Comment by SjoerdNijboer** [comment]
I can't tell you right now (I'm not sitting in front of my pc.) but I'm having trouble setting my compiler imports for the standard library / my source code. The error and problem looks like this [stackoverflow](http://stackoverflow.com/questions/20888257/gdc-error-error-module-file-is-in-file-file-d-which-cannot-be-read) post.
Thesame output is returned by intellij with dmd on windows.

**Comment by kingsleyh** [comment]
Ah I always use dub - which locates everything itself - are you using a non dub project?

**Comment by SjoerdNijboer** [comment]
I tried using a dub and a non dub project.
I have setten up dmd, dub, those four reccommended helper programs and have added them in intellij.
Unfortunately I do something wrong which I cannot figure out

**Comment by kingsleyh** [comment]
have you tried - creating the project with dub on the command line - and then in intellij using the import from existing sources option -> then choose dub when prompted.

**Comment by SjoerdNijboer** [comment]
see: https://github.com/kingsleyh/DLanguage/issues/122 for the result.

**Comment by SingingBush** [comment]
@SjoerdNijboer Can you try building the D plugin from source and installing that into IDEA rather than using the version in the repo. The version in the repo is a year old and there have been some fixes since then.

**Comment by SingingBush** [comment]
this has been updated a fair bit now and a newer version of the plugin is pending approval from Jetbrains
