### ISSUE TITLE
Add d standard library to sourcepath

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#127]
When setting up the compiler the sourcepath should be configured like so:http://imgur.com/a/F6sDB.
 This allows for easier resolving of methods from the standard library.

**Comment by pirocks** [comment]
The runtime library should also be included for optimal resolve functionality. This could be achieved by packaging the standard library with the ide.

**Comment by SingingBush** [comment]
the plugin could look for `dmd.conf` in the same way the dmd compiler does:

 - current working directory
 - directory specified by the HOME environment variable
 - directory dmd resides in
 - /etc directory

The file contains the path to phobos and druntime.  On my system (Fedora Linux):
/usr/include/dmd/phobos
/usr/include/dmd/druntime/import

**Comment by pirocks** [comment]
Issue closed because, this issue has been fixed.
