### ISSUE TITLE
std.stdio is not parsing correctly

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#129]
The title pretty much says it all. After the first `else version` statement The Psi seems to disintegrate into a list of tokens, instead of a syntax tree.

**Comment by kingsleyh** [comment]
you have skype? or another messenger we can have a quick chat on?

**Comment by pirocks** [comment]
Uh can't do video chat, but I can use gitter/hangouts/telegram

**Comment by kingsleyh** [comment]
gitter is good

**Comment by pirocks** [comment]
I don't really know where to put this comment, so I'll put it here. In order to improve the parser it could be a good idea to make use of the "private" keyword more. It would greatly simplify the psi tree, potentially making it easier to debug problems

**Comment by kingsleyh** [comment]
Yeah definitely - it was on my list - I'm still not sure though how it could look and what is needed to implement the other features like goto and refactoring etc

**Comment by pirocks** [comment]
This is fixed.
