### ISSUE TITLE
<project>.iml file

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#144]
Is there a need for the <project>.iml file to be in the project directory, can it not be in the .idea directory>

(Rust plugin gets this wrong as well. :-(

**Comment by SingingBush** [comment]
That's the default place for Intellij to put it. I personally like to have `*.iml` and `.idea/` in my gitignore file. If using dub there's no need for IDE specific files to be in version control.

**Comment by kingsleyh** [comment]
*.iml and .idea should really be in .gitignore anyway

**Comment by russel** [comment]
Interesting though that none of the JetBrains plugins leave a .iml file in the top level of a project.
