### ISSUE TITLE
highlighting lexer test fails

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#145]
@kingsleyh in commit https://github.com/kingsleyh/DLanguage/commit/d22414704db7c1faaa971e10ccc569e5cad85b77 I had to set the _DLanguageHighlightingLexerTest_ to be ignored as it fails. I presume it's been that way for some time as that class was never included in the DTestCase that was formerly used for specifying which test classes to run. 

It seems that the travis builds weren't actually running the tests so the commit I did was to ensure that and class ending with 'Test' is run as part of the build process and the results shown in build log.

Are you aware of any issues with the highlighting?

**Comment by kingsleyh** [comment]
I am not aware of any issues with the highlighting - but I haven't looked it for ages so .....

**Comment by SingingBush** [comment]
@pirocks is this something you can pick up?

**Comment by pirocks** [comment]
Sure.
