### ISSUE TITLE
Implement recover rules in bnf.

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#155]
Recover rules allow for recovering after a syntax error.
There is a guide on how to do this here:https://github.com/JetBrains/Grammar-Kit/blob/master/HOWTO.md

**Comment by SingingBush** [comment]
@pirocks I see you closed pull request #156 for this, any problems? I've setup a develop branch for merging in changes that will end up being in snapshot builds. I'm currently looking at getting anything built in develop to get published to the nightly channel in Jetbrains repo. When you're ready for merging do the PR against that branch.

**Comment by pirocks** [comment]
I made that pull request on accident. I was meaning to pull updates from master to my fork and got the order wrong.

**Comment by pirocks** [comment]
This is fixed by the new parser PR.
