### ISSUE TITLE
Braces not automatically closing

### ISSUE THREAD

**Issue by shad1w** [intellij-dlanguage/intellij-dlanguage#159]
Currently, IntelliJ IDEA (Community edition) doesn't automatically close braces when writing code in D.

For me, this is a much needed feature when writing code. Please consider implementing this in case it is not already implemented and just not working for me.

**Comment by pirocks** [comment]
The class that needs to be implemented is this: https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/codeInsight/highlighting/BraceMatcher.java

Added to my todo list.

**Comment by pirocks** [comment]
Update to the above comment:
This needs to be implmented:
https://upsource.jetbrains.com/idea-ce/file/idea-ce-d00d8b4ae3ed33097972b8a4286b336bf4ffcfab/platform/lang-api/src/com/intellij/codeInsight/editorActions/smartEnter/SmartEnterProcessor.java
and  Brace Matcher has already been implmented by DBraceMatcher

**Comment by shad1w** [comment]
I'll try implementing this and will see if this works.
Will comment again once I know.

**Comment by pirocks** [comment]
Any luck @shad1w?

**Comment by shad1w** [comment]
@pirocks Sorry for the late response.

Didn't have any luck with this yet but I didn't have much time recently either. I might be able to try this again in the next few days but after the last attempt, I doubt that I will be able to dig through IntelliJ's API anytime soon.

In case it exists at all and if anyone could provide me with a link to the Javadoc of IntelliJ's API, I think I'd be able to implement at least some hack-ish workaround but even then I doubt I could find the time to do this properly anytime soon.  
But from what I could find so far, it seems like there is no Javadoc anymore.

**Comment by pirocks** [comment]
I've been passively looking into implementing this, and the intellij documentation for this seems very limited. Basically all I've found in the official documentation is here http://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/additional_minor_features.html
There is also a few semi-relevant wiki questions here:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206769285-SmartEnterProcessor-for-custom-language
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206129589-Brace-matching-problem -- will check if this is an issue for this plugin.
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206114769-automatically-insert-closing-quote

**Comment by pirocks** [comment]
@kingsleyh , I was wondering if you know anything about this since, you implemented DBraceMatcher.

**Comment by pirocks** [comment]
I have asked the intellij forums about this, and hopefully will get an answer. https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000393430-Auto-closing-braces-in-a-custom-language

**Comment by shad1w** [comment]
So I followed the comment on your forums post and found out that the matched token type is different from the one provided by DBraceMatcher in 
`com.intellij.codeInsight.highlighting.PairedBraceMatcherAdapter` on line 61

![image](https://user-images.githubusercontent.com/22195087/28132938-a15671b2-673e-11e7-8621-f5e5e5dcee64.png)

![image](https://user-images.githubusercontent.com/22195087/28132954-ae213210-673e-11e7-91bd-e23ca5e87520.png)

Unfortunately I don't know how to fix this yet but I thought it would be best to add this info here until I figure out how to fix this.

**Comment by kingsleyh** [comment]
I can't remember why it's implemented as it is as I did it quite a few years ago - but feel free to change it

**Comment by shad1w** [comment]
I'll try to get this fixed but it'll likely take a long time since I don't have any experience whatsoever yet concerning JFlex and lexing in general.

**Comment by pirocks** [comment]
Sorry I'm not being very responsive/fast at fixing this. I've been working on a new parser(which imho is much higher priority), but when I'm done with that I'll get on this.

**Comment by pirocks** [comment]
About your screenshot: The "BRACES", are from the syntax highlighting lexer, aka: https://github.com/intellij-dlanguage/intellij-dlanguage/blob/master/src/main/java/net/masterthought/dlanguage/lexer/DSyntaxHighlightingLexer.flex , while the other one is from the regular lexer, aka: https://github.com/intellij-dlanguage/intellij-dlanguage/blob/master/src/main/java/net/masterthought/dlanguage/lexer/DLanguageLexer.flex . I'm not sure why the brace matcher is being passed syntax highlighting lexer tokens.

**Comment by pirocks** [comment]
Fixed in PR #207. @shad1w, your debugging was very helpful.

**Comment by shad1w** [comment]
@pirocks I can confirm it's fixed, thank you!
