### ISSUE TITLE
Everything is prefixed by DLanguage

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#160]
Numerous class names, especially those in gen/ are in the form DLanguage*. This can be a little annoying/verbose. Is this standard practice for an intellij plugin?

**Comment by SingingBush** [comment]
It doesn't have to be that way i suspect it's due to copying classes from another plugin and renaming them. It's fairly common in the plugins I've looked at. I'm in favour of at least shortening it to Dlang

**Comment by pirocks** [comment]
Some of them are caused by this line in the bnf: https://github.com/kingsleyh/DLanguage/blob/master/src/main/java/net/masterthought/dlanguage/grammar/DLanguage.bnf#L7

Others would need manual renaiming

**Comment by pirocks** [comment]
initial renaming done in commit https://github.com/pirocks/DLanguage/commit/2331b6fb207ddc9fdd241071c901e3e3fac4c91a

**Comment by pirocks** [comment]
An alternative to remaining everything wuld be to use type aliases, in kotlin

**Comment by SingingBush** [comment]
this is now mostly done. I've not renamed the classes in the gen folder though. Are those files still likely to get generated?

**Comment by pirocks** [comment]
The regenerated files are likely to be regenerated in the future. The regen script is in the gen folder and is called types_regen_script.d.

**Comment by pirocks** [comment]
Closing since this is mostly fixed
