### ISSUE TITLE
Nightly Update Channel

### ISSUE THREAD

**Issue by Scellow** [intellij-dlanguage/intellij-dlanguage#171]
Hello

IntelliJ Rust have two channel, one for stable release, and a nightly one

Would be could to have a nightly one so we don't have to manually compile/install the plugin :)

Thanks

**Comment by SingingBush** [comment]
this in in the pipeline. There should be _stable_, _eap_ and _dev_ builds but there's been issues deploying them to the Jetbrains repo.

**Comment by Scellow** [comment]
Awesome! Thanks a lot guys

**Comment by SingingBush** [comment]
we now have dev builds:
https://plugins.jetbrains.com/plugin/8115-d-language?pr=idea

**Comment by Scellow** [comment]
For people who wonder what is the url of the Dev channel (for intellij) it's this one:

https://plugins.jetbrains.com/plugins/Dev/8115-d-language/

Under the plugin menu, you have to click on the ```Manage repositories...``` button then copy paste that link
