### ISSUE TITLE
Can't install newly built plugin into IDEA 2017.2 EAP

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#179]
I just built the develop branch and tried to install the resultant plugin jar, but was not allowed to. I am guessing the plugin is somehow locked to 2017.1. Is there any way of having the plugin able to work with the latest EAP as well as the latest release IDEA?

**Comment by pirocks** [comment]
I haven't checked that this work, however try changing `<idea-version since-build="171"/> to `    <idea-version since-build="172"/>`, in plugin.xml.
`

**Comment by russel** [comment]
@pirocks The number 171 in src/main/resources/META-INF/plugin.xml appears to just be a placeholder, the value is always overwritten.

**Comment by SingingBush** [comment]
It shouldn't be getting overridden. If that is the case then we need to change gradle build to not override it.

**Comment by russel** [comment]
1.13-dev441 says it works for 171+ and indeed loads fine after download (is there a way of getting it to appear in the list without explicit download?). I just did a build of master but it will not install into IDEA 2017.2 EAP (which is 172). So clearly there is some magic in building the dev441 which is not available to a build grom Git clone.

**Comment by russel** [comment]
Looks like I can build from master and install into 2017.2 EAP just fine now.
