### ISSUE TITLE
A question about the lexer/parser.

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#185]
As far as I am aware Jflex does not support lookahead in regex. This makes lexing `7.` and `7..x` both correctly a challenge, since there is no way for the regex to know about the `.x` after `7.`. My current solution would be parsing floats in the parser(which would look something like `Float ::= (Integer? '.' Integer )| (Integer '.') `). Does anybody have alternate, less extreme solutions or does implementing in parser sound good?

**Comment by kingsleyh** [comment]
Does this help

https://github.com/moy/JFlex/blob/master/jflex/examples/java/java.flex

**Comment by pirocks** [comment]
Unfortunately not, however I was able to resolve this issue with some help from stackoverflow
