### ISSUE TITLE
IDEA plugin list still shows v1.10

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#187]
The plugin list presented by IntelliJ IDEA still shows DLanguage 1.10, there appears no mention of 1.12, nor of the 1.13 dev snapshots.

**Comment by kingsleyh** [comment]
You have to use a different plugin repository to get builds other than stable

**Comment by SingingBush** [comment]
1.12 will only show up if using 2017.1 as it was released before we sorted #179 
we need to do another release to get the new version to show up for users with 2017.2

We could do with ironing out a few problems before doing another release though.

**Comment by SingingBush** [comment]
We're deploying dev builds faster than Jetbrains are approving them. For this reason [I've removed the bit in travis.yml that handled dev branch deployments](https://github.com/intellij-dlanguage/intellij-dlanguage/commit/78f25555208ce35249c6fe525ac0db71fcb15f3d). Having the master branch deploy a eap version is still useful though so I've kept that as-is.

<img width="927" alt="screen shot 2017-06-05 at 22 14 41" src="https://cloud.githubusercontent.com/assets/870567/26803525/6fb71f54-4a3c-11e7-8b58-9952fbac92c4.png">

@kingsleyh when you have time can you remove the Dev channel builds from https://plugins.jetbrains.com/plugin/8115-d-language?pr=idea
