### ISSUE TITLE
No v1.12 release notes

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#188]
In the plugin list, the 1.13-SNAPSHOT plugin lists no change notes for v1.12, the last are for v1.11.

**Comment by kingsleyh** [comment]
Develop branch = EAP build
Master branch = Dev build
Tag = Stable build (default plugin repo)

**Comment by SingingBush** [comment]
when I expand the list on the plugins page they both have changenotes:
<img width="948" alt="screen shot 2017-06-03 at 17 11 56" src="https://cloud.githubusercontent.com/assets/870567/26755171/ed23f098-487f-11e7-92fa-3154fd0698e3.png">

It's old information extracted from the _plugin.xml_ - it needs to be updated before the next release.
