### ISSUE TITLE
Unexpected import

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#190]
The code fragment:
```
version(unittest) {
    import unit_threaded
```
causes a red line "import unexpected".

**Comment by pirocks** [comment]
On develop this does, however only because there is a missing semicolon and curly brace.

**Comment by russel** [comment]
The actual code in the file does have a semicolon, I just forgot it reporting here. Also the actual code have more and it does have a closing }. Perhaps I should have reported it as:
```
version(unittest) {
    import unit_threaded;
    …
} else {
    …
}
```
I am getting a whole slew of red lines after his, so it may just be a problem elsewhere. The code showing the problem is https://github.com/russel/ApproxGC/blob/master/source/main.d

**Comment by pirocks** [comment]
This issue occurs on the develop branch right?

**Comment by russel** [comment]
Yes, I am now building develop (plus my version updates) and installing it into IDEA.

**Comment by pirocks** [comment]
I have reproduced this issue, working on a fix.

**Comment by russel** [comment]
Splendid. Now you can reproduce it, I can worry less about how to describe the problem. :-)

I am now set up to do end user testing, and am slowly working up to actually doing some constructive stuff.

**Comment by pirocks** [comment]
Fix for this issue in PR #191.

**Comment by pirocks** [comment]
Is this still an issue/can the issue be closed?

**Comment by russel** [comment]
I believe this issue is fixed.
