### ISSUE TITLE
Don't build from working directory

### ISSUE THREAD

**Issue by mbierlee** [intellij-dlanguage/intellij-dlanguage#199]
When you change the working directory in a run configuration of a "Build with DUB" run, DUB will try to build from the working directory. In my project I need to change the working dir when running to a subdirectory to load assets into my program. 

DUB should always build from the project directory and then run at the working directory.

**Comment by mbierlee** [comment]
Also the working directory in a "Run D App" run config doesn't seem to properly set the working directory

**Comment by pirocks** [comment]
Just to clarify this is with version 1.12 of the plugin?

**Comment by mbierlee** [comment]
Yes, 1.12

**Comment by pirocks** [comment]
![image](https://user-images.githubusercontent.com/10455020/27185113-2d195c0c-5199-11e7-98b5-ead0b9bea3a5.png)
![image](https://user-images.githubusercontent.com/10455020/27185126-35b43468-5199-11e7-8c99-6378847d7f1f.png)
Does this dub.json achieve what you want?
