### ISSUE TITLE
Debugger 

### ISSUE THREAD

**Issue by kingsleyh** [intellij-dlanguage/intellij-dlanguage#20]

**Comment by SingingBush** [comment]
mostly done by https://github.com/intellij-dlanguage/intellij-dlanguage/pull/250

**Comment by andre2007** [comment]
Debugging is possible with https://github.com/intellij-dlanguage/intellij-dlanguage/pull/429.
This also enables debugging with WSL GDB and mago-mi.
I think this can be closed.
