### ISSUE TITLE
Why not package dcd,dfmt, dscanner, etc.. with the plugin

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#201]
This would simplify setup and give is more control over versions of dcd etc. Obviously we would need different dcd/dfmt/dscanner builds for different platforms. Alternatively we could compile dcd/dfmt/dscanner on first setup, which would allow for more platforms.

**Comment by Scellow** [comment]
Might worth it to look into this project:

https://github.com/Pure-D/serve-d
https://github.com/Pure-D/workspace-d

Instead of having to manage multiple binaries, and it seems like his project is doing really well

**Comment by pirocks** [comment]
Another thing including dcd/dscanner etc could do is make it easier to interface with d via JNI, which could improve performance/stability

**Comment by kingsleyh** [comment]
I think in the long term we should aim to get rid of DCD and DFMT and write IntelliJ solutions - in the short term we could try to improve them

**Comment by pirocks** [comment]
I have fairly decent PsiScopeProcessor based resolve and code completion in the works. However it will take a long time before it will be as good as dcd especially on the code completion side.

**Comment by pirocks** [comment]
https://github.com/Pure-D/code-d/issues/38. --relevant issue. It seems that when building dcd on windows it is best to build with ldc. Unfortunately we do not really have ldc support, so if we package dcd with the plugin we would need to have a prebuilt binary

**Comment by SingingBush** [comment]
I prefer getting rid of dcd/dfmt support altogether, however it's probably worth [investigating serve-d](https://github.com/intellij-dlanguage/intellij-dlanguage/issues/148).

**Comment by WebFreak001** [comment]
serve-d just uses DCD/dfmt too but if you want you can implement your own solutions directly into workspace-d (the library behind serve-d, can also be used as standalone application with an alternative protocol to Microsoft's language server protocol). I programmed it in a modular way that should make it easy to add in new providers. The plugin/serve-d choose what auto completer they are going to use and the auto completer gets the import paths from dub or fsworkspace or any other provider so it can provide the symbols.

**Comment by pirocks** [comment]
I'm going to try to package, dcd, dfmt etc. with the plugin, because I think that I can do it quickly and easily, and it would greatly decrease barrier to entry for using the plugin.

**Comment by SingingBush** [comment]
it adds an extra maintenance burden for us. They're easy enough to setup. If anything we could detect if they're not configured and have the UI let the user know with a link to the config screen to set them up. Even then, it's not something I'm that keen on as I'm in favour of removing them alltogether.

**Comment by pirocks** [comment]
>it adds an extra maintenance burden for us. 
Ok I won't do it.
>  I'm in favour of removing them alltogether
It will still be year(s) before we have the same level/quality of support as dcd/dfmt etc, meanwhile our plugin is harder to use/less good than other alternatives. Perhaps we should create some kind of high level plan as to how we're going to replace dcd etc., what features we want, and when we want them.
