### ISSUE TITLE
Gradle 5.0

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#203]
I just built the plugin with Gradle 4.0 and it is fine. However a small flag:
```
> Task :jps-plugin:instrumentCode
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
```

**Comment by SingingBush** [comment]
that seems like it'll be a pain for multi-language projects. guess we'll be sticking to v4.*

**Comment by russel** [comment]
For myself, I am quit happy separating the languages at the expense of disjoint packages, though I understand the viewpoint of people who prefer "centralising". I guess we have to see what the line is from Gradle Inc. Do they just get paternalistic authoritarian, or do they have a sensible plan. If the former then Gradle 5.0 will be a failure.
