### ISSUE TITLE
Running the Plugin in Debug mode

### ISSUE THREAD

**Issue by kingsleyh** [intellij-dlanguage/intellij-dlanguage#204]
Hi, 

I discovered this recently - you can run up the plugin in Debug mode to breakpoint on stuff using the gradle runIde task in the right hand gradle tab. 

![psbinderimpl_java_-_purity_-____dev_projects_intellij-purescript__and_slack_-_chupachupa](https://user-images.githubusercontent.com/103770/27496673-e91e7ff2-584e-11e7-9f6e-0b996f1f07c7.png)

**Comment by pirocks** [comment]
How is this different from making a run configuration and then running it with the debug icon?

**Comment by kingsleyh** [comment]
It's the same but it auto generates the run config so it's more convenient
