### ISSUE TITLE
d language errors are being detected in non-D source files

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#206]
I was reading the `README.md` of a D project that has some example code in it and noticed that the plugin is checking the file for syntax errors:
![screen shot 2017-06-30 at 12 21 52](https://user-images.githubusercontent.com/870567/27733631-05f5f570-5d8f-11e7-8bef-5f16ebac0825.png)
it should only be looking at files with `.d` extension (and maybe diet templates)

**Comment by kingsleyh** [comment]
Maybe it's not matching on the d properly and taking .md as a d file or something strange like that

**Comment by pirocks** [comment]
I think it's a feature, not a bug. Why markdown extension are you using?

**Comment by pirocks** [comment]
To clarify what I  mean by it's a "feature":
![sketch](https://user-images.githubusercontent.com/10455020/27743815-180c0898-5d72-11e7-8eb0-b76ae0964faa.png)

**Comment by SingingBush** [comment]
@pirocks I hadn't noticed that before. Just checked it with some Java and got auto complete etc. pretty nifty.
