### ISSUE TITLE
Taking a break

### ISSUE THREAD

**Issue by kingsleyh** [intellij-dlanguage/intellij-dlanguage#211]
Hey

Realistically I'm not going to be doing any more work on this intellij plugin so I'm handing over ownership to @SingingBush.

I suggest you create a new Jetbrains repo account and I will retire mine. I will also be leaving the project / organisation but will remain a user of the plugin. 

Thanks for picking up the coding and progressing it - I will look forward to seeing the improvements you make over time. It's been fun - but I'm taking a break from D to focus on other things.

--Kingsley

**Comment by SingingBush** [comment]
Cheers kingsley. I hope you're managing the work/life balance. It's probably worth keeping in the intellij-dlanguage group in case you get more time in future. Although saying that my little one is approaching two and I'm still struggling to find time for anything more than the odd merge and general maintenance. 
I have an account on the jetbrains repo as [singingbush](https://plugins.jetbrains.com/author/singingbush).

**Comment by russel** [comment]
@kingsleyh  Hope to see you back again in the D community again sometime in the future. Thanks for starting this work.

**Comment by pirocks** [comment]
Thanks for all the work you've done so far, and I hope that you enjoy what comes next.  Hopefully we will make good progress on making a great D IDE.

**Comment by Scellow** [comment]
Thanks a lot for all your hard work, it is not easy task to build/maintain such a project, i wish you all the best <3
