### ISSUE TITLE
Stop use of "masterthought"?

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#221]
This plugin talks about http://www.masterthought.net/ being the home location for the organisation developing this plugin. Surely the plugin should direct people to this GitHub repository. Especially as http://www.masterthought.net/ results in a 503 response.

**Comment by SingingBush** [comment]
references to that domain in comments/readme/release notes etc can all be changed. 

Package name can stay as-is for now. We should probably leave the _net.masterthought.dlanguage_ id in `plugin.xml` as changing it could cause problem when releasing new versions to plugin repo.

**Comment by pirocks** [comment]
What should we replace masterthought with?
Currently in the plugin.xml we have a "vendor name", and an official contact email. Do we need those, if so what should we replace them with?

**Comment by SingingBush** [comment]
https://intellij-dlanguage.github.io/ needs a bit of an overhaul. When we get around to changing package name then we should use groupid _io.github.intellij.dlanguage_

**Comment by SingingBush** [comment]
I think it would be good to do this for the next release. #160 and #253 need doing also

**Comment by SingingBush** [comment]
All the code has been moved into _io.github.intellij.dlanguage_ package. For now I've left the plugin id in _plugin.xml_ as _net.masterthought.dlanguage_ as it may affect getting releases out to the plugin repo.
