### ISSUE TITLE
"The JDK is not configured properly for this project. Inspection cannot proceed."

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#228]
![image](https://user-images.githubusercontent.com/10455020/29237712-01271e64-7ed9-11e7-94d1-335c02cd5dd5.png)

I get this message when running `Analyze > Inspect Code...` on projects created with `File > New > Project from Existing Sources ...`

**Comment by SingingBush** [comment]
Since my changes the path to DMD/dub would need to be relocated. It shouldn't be referring to JDK obviously, I suspect that is due to classes that are being extended.

**Comment by pirocks** [comment]
This is no longer an issue.
