### ISSUE TITLE
Adding libraries to project using "Process D Libraries" doesn't work anymore

### ISSUE THREAD

**Issue by mbierlee** [intellij-dlanguage/intellij-dlanguage#233]
Before it seems to be possible to add your DUB dependencies under "External Libraries" using the tool in Tools > Process D Libraries. This doesn't seem to happen anymore. In fact, when you manually add D libraries to your project, this command will remove them all.

On a side note, it would be nice if this process was automated (via a background process).

**Comment by pirocks** [comment]
@mbierlee Do you by any chance have a `.` character in your dub tool path?

**Comment by pirocks** [comment]
Pull request #270 should fix this. I am also considering automating this process with a background task.

**Comment by mbierlee** [comment]
@pirocks I don't have a . in my path. I am on windows though. Here's my path to dub:
C:\Dlang\dmd2-2.077.0\windows\bin

As you see, I use the dub supplied with the windows downloads

**Comment by pirocks** [comment]
I was referring to the dots in dmd2-2.077.0

**Comment by pirocks** [comment]
It's irrelevant though, because this should be fixed
