### ISSUE TITLE
Automatically add parentheses when autocompleting function calls

### ISSUE THREAD

**Issue by mbierlee** [intellij-dlanguage/intellij-dlanguage#235]
When autocompleting a function call, it will currently complete the function's name but doesn't conveniently add parenthesis to the code (| is the location of the cursor):

```d
public void someThing(string someText) { ... }

public void someOtherThing() {
    someThing|
}
```

It would be convenient to add parentheses to the function call and place the cursor within it: 

```d
public void someThing(string someText) { ... }

public void someOtherThing() {
    someThing(|)
}
```

Or place the cursor at the end when the function takes no parameters:
```d
public void someThing() { ... }

public void someOtherThing() {
    someThing()|
}
```

The same could be done when instantiating classes: `auto thing = new Class(|)`

**Comment by pirocks** [comment]
DCD already sorta does this AFAIK. This should be fairly simple to implement, except for the placing of the cursor.  I can make a PR for this now minus the correct placing of the cursor, or I can add it into my next big PR, which will come in about month, and have correct cursor placement.

**Comment by mbierlee** [comment]
I suppose we can forgo cursor placement for now, this is already more pleasant.
