### ISSUE TITLE
Dub started by plugin uses too much CPU

### ISSUE THREAD

**Issue by asampal** [intellij-dlanguage/intellij-dlanguage#239]
I'm running the following and see dub (v. 1.5.0) launched by the plugin consuming a good portion of CPU (~12.5%), keeping the fan going. This happens right from startup without having done anything, but with a D project automatically loaded. CPU stays high even after a longer wait, so it's not just a spike.

IntelliJ IDEA 2017.2.4
Build #IU-172.4155.24
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by pirocks** [comment]
Couple questions as I try to reproduce:

Is this using a specific dub project or is it also an issue with a blank dub project?
How was the dub project created? Was it created via new project in intellij, checked out from version control or imported?

**Comment by pirocks** [comment]
> This happens right from startup without having done anything, but with a D project automatically loaded.

Are you typing when the cpu usage is high or, or is it also high during idle?

>CPU stays high even after a longer wait
How long did you wait? This could be caused by the dub based syntax checker, which should eventually finish.

**Comment by asampal** [comment]
It happens during idle, and the project is a minimal D app, just generated with the new project wizard.

I waited quite a few minutes and CPU use didn't let up. There's not much syntax to check in the project - maybe 3 lines.

**Comment by pirocks** [comment]
I'm having trouble reproducing this, however there will be a plugin update soonish(see issue #240). There will be a lot of bug fixes/reworking/refactoring in this release so hopefully this problem will be fixed. Also are you sure its the dub process using lots of cpu? That seems strange to me, since dub doesn't really do anything cpu intensive(besides compiling which would be separate process).

**Comment by asampal** [comment]
Yes, it's dub, as you can see below:

![image](https://user-images.githubusercontent.com/281639/30242521-eb7320ba-9565-11e7-90cb-7df175a0a6fb.png)

**Comment by ZombineDev** [comment]
@asampal can you post more info about the dub process (like current working directory, command-line, environment, child processes info, etc)? That should help pinpoint exactly what dub is doing, so the bug can be more easily reproduced, isolated from IntelliJ.

**Comment by asampal** [comment]
Does this help?
![image](https://user-images.githubusercontent.com/281639/30258951-bc8218de-968b-11e7-9e34-2b4e315d36e8.png)

**Comment by pirocks** [comment]
I am still unable to reproduce this issue. What happens if you run dub build --combined -q from terminal?
There should be plugin update coming soon that might fix this problem.

**Comment by asampal** [comment]
Finally resolved this, but I'm unsure what exactly did it. When I first reported this issue, I was using plugin version 1.13. I tried running dub from the command-line, in that project and got the same high cpu use outside of Idea. The output I saw was the following (I had to ctrl-C to halt the process):

![image](https://user-images.githubusercontent.com/281639/30301587-a6696e46-9729-11e7-873c-cd3f8dd7ad07.png)

I just now downloaded 1.13.1 since Idea wasn't reporting a newer version than 1.13, and installed from the zip and created a new dub-based starting project (minimal). This time Idea didn't automatically start on project loading and also the command-line execution of dub didn't report the above error.

I'm not sure if there was a bug in 1.13 that created a project in an invalid state, but the new plugin seems to produce a proper project.

**Comment by pirocks** [comment]
Thanks for the bug report. The update is still waiting Jetbrains approval, which is why Idea hasn't reported a newer version. Please don't hesitate to submit other reports if you find more bugs. Feature requests are also welcome.

**Comment by SingingBush** [comment]
@asampal also worth noting that in the new version you will need to set the path to dmd again. the plugin now wants the root directory of dmd instead of the exe

**Comment by asampal** [comment]
@SingingBush I assume you're talking about 1.14 and not 1.13.1 which I'd just installed. The latter seems to still autofind and set the complete path of dub, including the exe.

**Comment by pirocks** [comment]
AFAIK it finds the full path in windows but still correctly gets the root directory path.

**Comment by SingingBush** [comment]
yes the dub path is the same, it's just the windows path to dmd that is setup differently.
