### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#240]
Will the next plugin release wait until the next intellij update, or will there be a release before that?

**Comment by SingingBush** [comment]
I'm fine with doing a release before then. Just not had time to work on any issues recently as have two week deadline for something else I'm working on.

**Comment by pirocks** [comment]
There are a few things I want to fix/change before a new release. I'll make a PR for those things today.

**Comment by pirocks** [comment]
PR Mentioned in previous comment is here: https://github.com/intellij-dlanguage/intellij-dlanguage/pull/242/files
