### ISSUE TITLE
Compile check uses dub for compilation checking, dmd -o- would be faster

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#241]
Calling `dmd -o-`, would likely give faster error checking than dub, while also not writing object files. This may be related to/ a fix for #239.

**Comment by mbierlee** [comment]
What about people not using DMD but LDC/GDC instead? Though unlikely that D developers don't have DMD installed, this is a possibility.

**Comment by russel** [comment]
More than a possibility, I always install LDC and GDC, I try to avoid installing DMD.

**Comment by ZombineDev** [comment]
Both LDC and GDC support this option. LDC uses the same syntax  as DMD `-o-`, while GDC mimcs GCC's `-fsyntax-only`.

**Comment by pirocks** [comment]
This would require ldc/gdc support so closing for now.
