### ISSUE TITLE
Failed upload to Jetbrains plugin repo

### ISSUE THREAD

**Issue by kingsleyh** [intellij-dlanguage/intellij-dlanguage#244]
It came to our attention that JetBrains Plugins Repository API outage has affected the update you uploaded for the plugin D Language:
1.13.1 on 2017-09-11 13:32:28

Please read on, as plugin update should be re-uploaded to be made available to plugin end-users.

The incident on the plugins repository side occurred on Monday, September 11, 2017, at 10:18 am CEST. It affected a small number of plugin authors using the API to upload updates to the plugins repository. Due to a bug in the API backend, plugin updates uploaded via the API (more specifically https://plugins.jetbrains.com/plugin/uploadPlugin) have not been saved in the plugins storage and have become inaccessible for end-users (meta information has been saved in the database, but the file itself was not preserved).

The team has already fixed the issue and deployed the fix to production (on Tuesday, September 12, 2017, at 3:40 pm CEST). We have removed the unavailable update (listed above) from the repository, and would like to kindly ask you to upload the missing updates again via the API or manually.

Thank you for your collaboration, and we are sorry for the inconvenience caused. Please feel free to reach out to us for assistance or additional information about matters related to the plugins repository.

**Comment by SingingBush** [comment]
@kingsleyh thanks for that. I've kicked the build off again so it should get uploaded again shortly.

**Comment by SingingBush** [comment]
seems to have been approved https://plugins.jetbrains.com/plugin/8115-d-language?pr=idea
