### ISSUE TITLE
use more friendly message when a keyword has been used in a module name

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#255]
![expected_dlangtokentype](https://user-images.githubusercontent.com/870567/30641957-c99ffc30-9e00-11e7-87ca-4d10492f3000.jpg)

if you attempt to use a keyword as part of a module name you'll encounter an error but the message could be a bit better

**Comment by pirocks** [comment]
Would `Expected "ID" instead of "module"` work?

**Comment by SingingBush** [comment]
I was thinking something like "keywords cannot be used in module names". I didn't see the code that causes the message so don't know what's involved. Dropping the DlangTokenType from the message would be better than it currently is.

**Comment by pirocks** [comment]
The error is from `DLangParser.java:8481`. It's a generic error for any kind of unexpected token. I can remove the `DLanguageTokenType` fairly easily but anything else would be more involved. Certainly doable, but still more involved.
