### ISSUE TITLE
Autocompleting imports incorrectly completes full qualifier

### ISSUE THREAD

**Issue by mbierlee** [intellij-dlanguage/intellij-dlanguage#257]
When importing d modules and autocompleting them, the IDE incorrectly autocompletes the fully qualified name of the module when you've already typed part of the package name and the period.

Before autocompletion (| is the cursor):
```d
import std.bitm|
```

After accepting the suggestion "std.bitmanip":
```d
import std.std.bitmanip|
```

When you autocomplete from `import std|` it will complete correctly.

Plugin version v1.13.1
IntelliJ 2017.2.5

**Comment by pirocks** [comment]
Noted. I will fix this in the coming week.

**Comment by pirocks** [comment]
Submitted a PR for this. The PR fix only applies to import declarations. aka it won't work in module names or full name symbols.
