### ISSUE TITLE
Keyword "string" seen as "Possibly undefined symbol"

### ISSUE THREAD

**Issue by mbierlee** [intellij-dlanguage/intellij-dlanguage#258]
The IDE shows the in the title mentioned warning when using the string keyword anywhere in the code. This is of course incorrect, "string" is a builtin.

The warning is not shown for other types, such as int, float, etc.

**Comment by pirocks** [comment]
Try reinstalling the plugin. This is likely caused by an old d sdk definition with a new plugin version.

**Comment by pirocks** [comment]
![image](https://user-images.githubusercontent.com/10455020/31047001-b8a84d04-a5fa-11e7-8659-be92948b3c45.png)


Does your File > Project Structure > SDKs > Sourcepath, look the same as in the screenshot and/or does the sourcepath point to the druntime and libphobos sources?

**Comment by mbierlee** [comment]
My druntime path didn't point to import/. After fixing this the issue is resolved.

**Comment by pirocks** [comment]
I'm curious as to why reinstalling didn't fix this. I would have thought It would have made a new sdk with correct paths.

**Comment by mbierlee** [comment]
I didn't have to reconfigure the SDK after reinstalling. I reinstalled the plugin from the project selection screen, not from an opened project.
