### ISSUE TITLE
Odd syntax highlighting when referring to members which start with an underscore

### ISSUE THREAD

**Issue by mbierlee** [intellij-dlanguage/intellij-dlanguage#259]
In the dark theme, when referring to members which start with an underscore, the period and underscore are colored blue instead of the usual white:

![image](https://user-images.githubusercontent.com/1678927/31097743-ae291d50-a7c0-11e7-8501-3f8de7b64326.png)

The access modifier (private in this case) doesn't seem to influence it.

**Comment by pirocks** [comment]
This is caused by  ._ being lexed as a number. This would be a fairly easy fix.

**Comment by pirocks** [comment]
`._` is lexed as number because d allows underscores in numbers to help keep track of magnitudes (aka its easy to see that `1_000_000` is a million).
