### ISSUE TITLE
GDB support

### ISSUE THREAD

**Issue by bamarc** [intellij-dlanguage/intellij-dlanguage#287]
The patch-note of 1.14 mentions GDB but i cannot figure out how it works. 
Is this feature already working and if yes, how do i use it?

**Comment by pirocks** [comment]
Have you specified the path to gdb in Settings> D Tools?
Are you getting some kind of error message?

**Comment by pirocks** [comment]
Step 1: Make sure the path to gdb is configured
![image](https://user-images.githubusercontent.com/10455020/32905748-c86637fc-caf2-11e7-9571-a88316b08486.png)
Step 2: Set a breakpoint
![image](https://user-images.githubusercontent.com/10455020/32905814-fc61597e-caf2-11e7-8015-9762d8f8fd21.png)
Step 3: Hit the debug button in the top right.Your code should compile and run till the first breakpoint.
![image](https://user-images.githubusercontent.com/10455020/32906348-8ecace02-caf4-11e7-8405-0644f3870be7.png)
From there you should be able to look at stacktraces, variable values, single step etc.

**Comment by pirocks** [comment]
I would recommend you use gdb version 7 if you aren't already using it.

**Comment by bamarc** [comment]
Seems like a broken projektfile on my side. 

![screenshot_20171116_191546](https://user-images.githubusercontent.com/12558068/32908056-abe98830-cb02-11e7-9e81-bc05c1b2c6ac.png)

I tried creating a new DUB project wich worked perfectly. No Idea what's wrong with this one though.

**Comment by bamarc** [comment]
Found the reason: dub generates all lowercase executable files but in the IDEA Project File there were uppercase letters. GDB tried to use the project name from the IDEA File which was different from DUB

**Comment by pirocks** [comment]
You should be able to run commands in the gdb console, so you can set the correct file,

**Comment by bamarc** [comment]
I never really used gdb from cli so i'm not well versed with the commands.^^
Nethertheless got it running now.

**Comment by pirocks** [comment]
Ok I'll get around  to fixing this issue.

**Comment by pirocks** [comment]
See #305 for debugger executable name issues.
