### ISSUE TITLE
Debugger should provide a more user friendly notification if gdb path not found.

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#304]
Currently it complains about an @NotNull parameter, instead of informing the user that gdb is not configured.

**Comment by SingingBush** [comment]
is that the _@NotNull_ in the _Gdb_ contructor?  That should definitely be marked as _@Nullable_ as it called with `m_gdb = new Gdb(ToolKey.GDB_KEY.getPath(project), project.getBasePath(), this);` but `ToolKey.GDB_KEY.getPath(project)` can return null.

**Comment by pirocks** [comment]
Yes it is, but it should remain not null because creating a gdb object
without a path to gdb does not make much sense. Instead I should add a
check for null and complain to the user.

**Comment by bamarc** [comment]
I would like to try this one. It seems simple enough.

**Comment by pirocks** [comment]
> I would like to try this one. It seems simple enough.

Go for it.

**Comment by bamarc** [comment]
fixed in [311#](https://github.com/intellij-dlanguage/intellij-dlanguage/pull/311#issuecomment-347038937)
