### ISSUE TITLE
Template mixin not displays in structure view

### ISSUE THREAD

**Issue by sysint64** [intellij-dlanguage/intellij-dlanguage#307]

**Comment by pirocks** [comment]
Are you referring to template mixin declarations:
```d
mixin template foo{
int bar;
//some more code
} 
```
Or named template mixins:
```d
mixin foo!() Bar;
Bar.bar //access member of mixin
```
Or regular string/template mixins?

**Comment by sysint64** [comment]
> Are you referring to template mixin declarations:

this, but regular string/template mixins also not displays, but I'm not sure that this should be displayed in structure view.
