### ISSUE TITLE
Intellij 2018.* support

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#321]
There's now a _181-SNAPSHOT_ in https://www.jetbrains.com/intellij-repository/snapshots so I've added it to the travis builds. 

It's worth trying the snapshots over the next few months and keeping tracking of potential problems here. When running locally make sure to edit the _plugin.xml_ to say `until-build="181.*"`

If there's no breaking changes and we can continue to support everything since 172 that's great but if not we should consider the v1.16 milestone the point that we increase the min supported Intellij version

**Comment by SingingBush** [comment]
looks like we'll need a lot of changes. See https://travis-ci.org/intellij-dlanguage/intellij-dlanguage/jobs/320932792

for v1.16 I've set Intellij 2017.3 as min supported version but we may need a clean break and just support 2018.* versions.

**Comment by pirocks** [comment]
I think some of those exceptions should be fixed on intellij's side of things, not ours, though I'm not really sure what is causing them.

**Comment by SingingBush** [comment]
just ran develop branch against latest 181-SNAPSHOT on local machine and it seems to work ok

**Comment by SingingBush** [comment]
Jetbrains list API changes here:
https://www.jetbrains.org/intellij/sdk/docs/reference_guide/api_changes_list.html#changes-in-intellij-platform-20181

we should be fine to release 1.16 as `until-build="181.*"`
