### ISSUE TITLE
Upload new release on GitHub?

### ISSUE THREAD

**Issue by Scellow** [intellij-dlanguage/intellij-dlanguage#322]
Hello

The plugin page ( https://plugins.jetbrains.com/plugin/8115-d-language )  is constantly outdated, the plugin review system is really slow

Is it possible to have the releases uploaded on GitHub in the release section ?

Thanks!

**Comment by SingingBush** [comment]
I did put builds on the [release page](https://github.com/intellij-dlanguage/intellij-dlanguage/releases) a while ago but stopped as didn't think it worth while. I can start doing it again but it generally only takes 3-4 days for a release to get approved.  If you've cloned the repo you can get an up to date build by simply running `./gradlew buildPlugin`
