### ISSUE TITLE
null pointer in DLangParser

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#326]
```java
    private Token current() {
        return tokens[index];
    }
```

this method can return null. which in turn means that there's various places in the class that could get a NullPointerException.

I've annotated it with `@Nullable` and [fixed the bit that affected me](https://github.com/intellij-dlanguage/intellij-dlanguage/commit/4b8b248232cda6b7274599572182740f01920336). The annotation has highlighted a fair few problems though.

**Comment by pirocks** [comment]
If any elements of the token list are null, that implies that a token without a type is being lexed, which is the underlying bug/problem. In other words current() should never return null unless something went wrong earlier.

**Comment by SingingBush** [comment]
is it worth handling the potential for the token being null in the meantime?

**Comment by pirocks** [comment]
Perhaps, however it is likely a massive amount of work, since current is used in so many places.

**Comment by pirocks** [comment]
Do you happen to have the source of the file that caused the NPE?

**Comment by SingingBush** [comment]
I don't recall exactly but around that time I was looking at [ddbc](https://github.com/buggins/ddbc) and [mysql-native](https://github.com/mysql-d/mysql-native/)
