### ISSUE TITLE
Incorrect "possibly undefined symbol" when module declaration mismatches filesystem placement

### ISSUE THREAD

**Issue by mbierlee** [intellij-dlanguage/intellij-dlanguage#335]
When a module declaration in a D module file does not match its placement on the filesystem, the warning "possibly undefined symbol" is shown on the namespace parts. I don't think this warning matches up the actual situation, especially since modules don't have to match filesystem placement.

Example:
Place a D file in  the source root, then declare it as `module somenamespace.modulename;`, the aforementioned warning is shown on `somenamespace`.

**Comment by pirocks** [comment]
I agree. I'll fix in next release

**Comment by pirocks** [comment]
Fixed in 48290df.
