### ISSUE TITLE
License

### ISSUE THREAD

**Issue by VISTALL** [intellij-dlanguage/intellij-dlanguage#336]
Hi guys. Can you provide license for project? (Apache 2 or MIT). Please create LICENSE.txt in project root. 

I wanna fork your project for my IDE, and don't wanna break any your rights:)

Thanks

**Comment by pirocks** [comment]
Top contributors to this repo are:
@pirocks @SingingBush  @kingsleyh @sysint64 @mbierlee @russel 
We should probably all agree on a license before adding one.

**Comment by SingingBush** [comment]
I'm in favour of GPLv3

**Comment by mbierlee** [comment]
I would be in favor of MIT (or Apache), but since this is not a lib I can live with GPLv3 too.

**Comment by VISTALL** [comment]
Guys be careful. You already linked MIT code (gdb). In future maybe you will link to CLion code (which is proprietary software) - for using some implementation link debugger or C++ analyzer.

Thanks.

Happy New Year.

**Comment by pirocks** [comment]
I'm fine with both GPLv3 and MIT

**Comment by sysint64** [comment]
I think MIT more suitable license

**Comment by pirocks** [comment]
Unless there are any objections I'll add an MIT license to this project in a week.

**Comment by pirocks** [comment]
License added.
