### ISSUE TITLE
Do not mark dynamic DUB version definitions as "possibly undefined symbol"

### ISSUE THREAD

**Issue by mbierlee** [intellij-dlanguage/intellij-dlanguage#340]
This is a tricky one, since it's not part of the d language itself. The IDE marks all dynamic DUB versions as "possibly undefined symbol", which is not incorrect but somewhat bothersome. 

![image](https://user-images.githubusercontent.com/1678927/34467870-db45447a-eefc-11e7-8b44-d93dd2855a5a.png)

Perhaps we can hack in an exception for versions following the pattern `Have_*`?

**Comment by sysint64** [comment]
I think that we should turn off this highlight for the version

**Comment by SingingBush** [comment]
how about registering the problem as _ProblemHighlightType.WEAK_WARNING_ instead of the default _ProblemHighlightType.GENERIC_ERROR_OR_WARNING_ if it's within version

**Comment by pirocks** [comment]
All version conditions are now marked as weak warnings(aka the same as spelling mistake warnings).
