### ISSUE TITLE
Latest language features marked as syntax errors

### ISSUE THREAD

**Issue by the-Mitu** [intellij-dlanguage/intellij-dlanguage#345]
There are at least two cases, where syntax errors are detected incorrectly due to the changes in the latest versions of D:

- [ ] **static foreach** (introduced in 2.076)
- [ ] **do** instead of **body** in function with contracts defined (introduced in 2.075, body to be deprecated someday)

**Comment by pirocks** [comment]
Fixed in d0bdb8f3a1814adc7a0f50ba1a92cb4173693181 and 61e8ecc0b89cd866c16fc4ce0608d34fc93bba21 respectively.
