### ISSUE TITLE
Implement background running of "Process D libraries"

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#352]
Ideally this would run in the background similar to indexing.

**Comment by SingingBush** [comment]
this should also run automatically when first opening a dub project.

**Comment by pirocks** [comment]
Agreed, I'm halfway through implementing this, and wondering how to handle project created in a previous version of the plugin, which may/may not have everything set up correctly.

**Comment by SingingBush** [comment]
The dub file could be processed on project load whether it's being imported or opened. We should also be watching dub.json/sdl and dub.selections.json for changes and prompting the user to import changes - the same way that the Maven/Gradle integration does.
I had a go at getting it to work before xmas but never finished it.

**Comment by SingingBush** [comment]
also, the current _ProcessDLibs_ requires the user to specify which module to process. From what I remember the dub import now handles multi-module project.

ProcessDLibs is used by the Dub Tool Window #149 that is also unfinished

**Comment by pirocks** [comment]
Done in 877f582c8e17a9d6a93412aae83da5836767ac9b and 877f582c8e17a9d6a93412aae83da5836767ac9b.
