### ISSUE TITLE
Support for /+ those +/ and /++ those +/ comments

### ISSUE THREAD

**Issue by the-Mitu** [intellij-dlanguage/intellij-dlanguage#353]
D has an additional set of block comments, which support nesting. They are currently not recognized by the editor at all, thus generating syntax errors.

**Comment by pirocks** [comment]
I'm not near a computer right now, but I thought these where supported.

**Comment by pirocks** [comment]
I'm not near a computer right now, but I thought these where supported.

**Comment by the-Mitu** [comment]
It does not generate syntax error - my mistake, sorry.
But they are not highlighted at all a comments.

**Comment by the-Mitu** [comment]
I believe that the issue is still valid, as these comments are not highlighted in the editor.

**Comment by pirocks** [comment]
4084491, adds highliting in editor for block comments.
