### ISSUE TITLE
IntelliJ IDEA 2018.1 EAP released

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#354]
Now that 2018.1 EAP is out those using it cannot use the D plugin due to the version check.

Let me know what I can do so as to verify there is not a problem and that the released plugin can be enabled for this version of IntelliJIDEA.

**Comment by SingingBush** [comment]
the development branch should work fine with 2018.1 - Can you build/install from source and report any problems.

**Comment by SingingBush** [comment]
will keep #321 for anything 2018.1 related
