### ISSUE TITLE
Could you remove the keyword "body"?

### ISSUE THREAD

**Issue by andre2007** [intellij-dlanguage/intellij-dlanguage#365]
Did you already considered removing the keyword "body"?
In your D modules you can already use the identifier body.

**Comment by pirocks** [comment]
So if I'm understanding correctly:
```d
int body = 0;
```
and 
```d
void a_function()
in{
}
body{
}
```

Are both valid?

I'm hesitant to remove the keyword completely, but I may hack the parser to accept it as both a keyword and identifier.

**Comment by pirocks** [comment]
I will probably implement a warning along the lines of `body` is deprecated.
