### ISSUE TITLE
Please choose the location of your dub binary

### ISSUE THREAD

**Issue by andre2007** [intellij-dlanguage/intellij-dlanguage#369]
While creating a new dub project / import existing project there is always the dialog asking for the dub binary.
This dialog is superfluous because of 2 reasons:
- in the previous screen I selected the DMD32 D Compiler which already points to the directory of dub
- in D tools settings screen I entered the path to dub.

It is quite annoying to press every time on the Auto find button.

**Comment by pirocks** [comment]
> in the previous screen I selected the DMD32 D Compiler which already points to the directory of dub

I believe this is not the case on all platforms/installations. However I agree that when possible dub should be loaded from there.

>While creating a new dub project / import existing project there is always the dialog asking for the dub binary.

This is the case because in the past D tools where project specific. This can be fixed.
