### ISSUE TITLE
Major issue while writing windows x86_64 applications

### ISSUE THREAD

**Issue by andre2007** [intellij-dlanguage/intellij-dlanguage#374]
In my dub.json I set as targetPath for the executable to "./bin". Within this folder I also copied the 64 version of libcurl.dll. In IntelliJ I created a "Build with dub" configuration with the name "build" and the architecture x86_64. While executing this configuration a 64 bit executable is created which is working fine.

But a few seconds later, IntelliJ replaces this 64 bit executable with a 32 bit executable and I cannot find out why and how to stop it / configure it. For my application I suddenly get a warning from windows that the 64 bit libcurl.dll doesn't fit to the 32 bit executable.

**Comment by pirocks** [comment]
This is likely something in the new dub auto detecting of changes to dub.json.

**Comment by andre2007** [comment]
Maybe also related to this issue. Every action in the Build main menu causes a x86 build. It seems I do not have any options to influence the architecture within jntellij. Unfortunately  dub does not allow to set the architecture within dub.jsonhttps://github.com/dlang/dub/issues/1327

**Comment by pirocks** [comment]
Can you try setting a dub flag for a 64 bit build here:
![image](https://user-images.githubusercontent.com/10455020/36225742-8f3ba8d2-11c3-11e8-83bc-aab092684290.png)

**Comment by andre2007** [comment]
I set the flags input field to value "--arch=x86_64" and even restarted IntelliJ. The flag seems to be ignored while clicking on "Build" actions (Build project, Rebuild project, ....)
Within folder .dub/build only the x86 debug binary is build (I can see it at the folder name
"application-debug-windows-x86-dmd_2078-69E1E3402796179A83043DB239D08883" )

In general maybe it makes sense if I could set the architecture on project settings,

**Comment by pirocks** [comment]
I'll look into this, this coming weekend.

**Comment by pirocks** [comment]
Sorry, for the long delay. It seems that this will be tricky to fix, due to many different, inconsistent ways of calling dub. I still hope to have a fix for this in the next release.

**Comment by andre2007** [comment]
The root cause of this issue was solved with #453.
