### ISSUE TITLE
Implment ProjectSdkSetupValidator

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#381]
A ProjectSdkSetupValidator is responsible for informing the user that the sdk is not correctly setup.

**Comment by pirocks** [comment]
Sample implmentation at `com.intellij.codeInsight.daemon.impl.JavaProjectSdkSetupValidator`

**Comment by SingingBush** [comment]
did this the other night but didn't push as the notification doesn't leave after selecting a valid compiler. Will commit what I've done as problem could be elsewhere.

**Comment by SingingBush** [comment]
there's no logic in my code to detect if dmd is setup as I presumed intellij would check against _DlangSdkType_ but that doesn't have any kind of isValid() method so maybe it does have to be in here. Thing is, I had also looked at _JavaProjectSdkSetupValidator_ and that doesn't actually do anything to check that the JDK has been setup.

**Comment by pirocks** [comment]
When creating this issue I was hoping we would provide clearer warnings when the dmd path is set incorrectly(see #362 ), as well as warnings for if standard library paths are not defined.

**Comment by pirocks** [comment]
This has been implemented in a number of commits. Most recent commit: 1c7a378
