### ISSUE TITLE
Dub running GDC's cc1d: Memory usage goes haywire

### ISSUE THREAD

**Issue by ibroheem** [intellij-dlanguage/intellij-dlanguage#396]
Anytime I initiate a project or click "Run DUB", cc1d gets started with high memory usage which never goes down.
I don't know if OS OOM-killer does it work or DUB or cc1d actually completes, 'cos everything grinds to a halt.

IntelliJ: IdeaIC2017.3
DLanguage: 1.16.1

Edit: I went ahead and disabled cc1d then I have this:
`dub run --build-mode separate
Failed to invoke the compiler gdc to determine the build platform: gdc: error trying to exec 'cc1d': execvp: No such file or directory`

Why is gdc being invoked in the first place?

**Comment by pirocks** [comment]
Can you try running `dub run --build-mode separate ` from the command line on the same project.

**Comment by ibroheem** [comment]
Yeah, I did run it on CLI and it ran fine on the CLI.

But here is a caveat, when I remove | rename `cc1d` to something else I get:
`Failed to invoke the compiler gdc to determine the build platform: gdc: error trying to exec 'cc1d': execvp: No such file or directory`

`cc1d` is located at `/usr/lib/gcc/x86_64-linux-gnu/6/`

**Comment by pirocks** [comment]
Have you tried compiling with a compiler option other than gdc enabled like so:
![image](https://user-images.githubusercontent.com/10455020/36935708-d849eb7e-1ef2-11e8-9395-92034fb4f2c2.png)

**Comment by ibroheem** [comment]
That works!

**Comment by pirocks** [comment]
Ok. Closing for now. Feel fre to reopen, if the issue persists/you need to use gdc.

**Comment by ibroheem** [comment]
No problem!
Thanks.

**Comment by ibroheem** [comment]
Now I'm Back with accurate info, calling cc1d only happens:
1. When I don't create project using the "D Application with DUB" or "D Application" option; and specifically using the File -> "Open" (in my case).
2. Even when I use the "D Application with DUB" or "D Application" option, I still had to set the compiler option to dmd (the absolute path).

It's using the gdc cc1d to do some platform querying, hence generating a "dub_platform_probe-xxxx-xxx-xxx.o" file.
But whenever I use  "D Application with DUB" and set the compiler to DMD, cc1d doesn't run anymore

I hope this helps.

Thanks
