### ISSUE TITLE
D, IntelliJ IDEA, CLion, and Rust

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#397]
I have been doing a lot of Rust recently, but will come back to D soon. As we all know JetBrains made the Rust plugin to IntelliJ IDEA an official JetBrains project. It works very well. It is a pity JetBrains doesn't make the D plugin official so it can get the same support.

An observation or two: JetBrains support the D plugin in IDEA but all the emphasis is now on CLion. Indeed the home for Kotlin/Native is CLion. The rationale seems to be debugging. Native code debugging is not something supported in IDEA, but it is in CLion. I can attest that even in its very early stges Rust debugging in CLion is almost as good as C and C++ debugging in Rust. The CLion Rust plugin supports Cargo, it does not require CMake. I have no idea if under the covers they use a CMake project or not, but I am definitely using Cargo not CMake to work this CLion project.

A proposal or two: I think the intellij should be dropped from the project title. I think that as, with the Rust plugin, the D plugin should focus on CLion and not IDEA exactly because that is where the debugging support is and seemingly always will be. The plugin should be available in IDEA as well but clearly with no debugging support.

So to the question: what do people think about continuing with IDEA support for the C plugin but shifting emphasis to CLion using Dub?

**Comment by SingingBush** [comment]
We have a branch for [multi product support](https://github.com/intellij-dlanguage/intellij-dlanguage/tree/feature/multi-product-support) in which I've made some recent steps towards getting the plugin working in CLion (although it's early days), see #57. Jetbrains provide a mechanism for plugins to add functionality for specific products so we can have different functionality for CLion if needed

https://github.com/intellij-dlanguage/intellij-dlanguage/blob/dbec2821101023f3f8ae296d76a8842e11512791/src/main/resources/META-INF/plugin.xml#L42-L48
