### ISSUE TITLE
Apt repository used in CI is frequently unavailable. 

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#403]
Both pull requests #400 and #339, are failing because the connection to  `http://master.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list` times out.

**Comment by SingingBush** [comment]
Sourceforge have issues due to their data centre having some kind of power problem that damaged hardware

**Comment by pirocks** [comment]
Ok. Closing for now, will reopen if this remains an issue.
