### ISSUE TITLE
There should be a global lock on Dub.

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#407]
Dub does not allow for multiple concurrent builds on the same project. This can be an issue if the annotator for dub compilation checking is running concurrently with a user build.

**Comment by andre2007** [comment]
This issue might be solved with PR https://github.com/intellij-dlanguage/intellij-dlanguage/pull/453.
There are not longer binaries created during dub compilation check.

**Comment by pirocks** [comment]
Closing for now. Future features might still need some kind of lock.
