### ISSUE TITLE
Call dub and other tools (gdb) within shell

### ISSUE THREAD

**Issue by andre2007** [intellij-dlanguage/intellij-dlanguage#423]
The intellij-dlanguage plugin calls dub without the shell option.

As comparison, in Phobos there are 2 different functions "execute" and "executeShell". The intellij-dlanguage plugin uses s.th. similiar to the "execute" function and therefore extended shell functionality is not available.

Reason for this request: Windows provide a functionality called "Windows sub system for linux". Within windows there is linux (ubuntu) running. From a Dos prompt I can call the command "wsl dub". The command "wsl" will pass the arguments to the linux subsystem and calls dub within linux. This allows me to easily create linux binaries from my windows system (dos prompt).

I want to check whether it is possible to use Intellij on my windows machine, while all the compiled artifacts will be for linux (by entering as dub file path: wsl dub). 
My goal at the end is to use gdb (which runs on the linux subsystem).

![image](https://user-images.githubusercontent.com/1451047/40889841-a237c57e-676d-11e8-82f8-f785445eda74.png)

This won't work because dub is called without shell option:

```Unable to parse dub configuration: Cannot run program "c:\windows\system32\wsl dub" (in directory "C:\gdbtest"): CreateProcess error=2, The system cannot find the file specified

com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "c:\windows\system32\wsl dub" (in directory "C:\gdbtest"): CreateProcess error=2, The system cannot find the file specified

                at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:395)

                at io.github.intellij.dlanguage.project.DubConfigurationParser.parseDubConfiguration(DubConfigurationParser.java:138)

                at io.github.intellij.dlanguage.project.DubConfigurationParser.<init>(DubConfigurationParser.java:62)

                at io.github.intellij.dlanguage.project.DubProjectImportBuilder.buildModules(DubProjectImportBuilder.java:135)

                at io.github.intellij.dlanguage.project.DubProjectImportBuilder.lambda$commit$0(DubProjectImportBuilder.java:103)
```

**Comment by bamarc** [comment]
I believe this is because the IDE searches for the dub executable file to run it directly. I don't know if it is compatible with the linux subsystem, especially because in debug mode the debugger attaches itself to the running process. I have no idea if this works with the linux subsystem.

**Comment by andre2007** [comment]
The path to dub you can specify in the settings. The only issue is, while calling dub, enhanced shell functionality is currently not available which causes the command "wsl dub" to fail.

My workaround is to create a batch file "dubwsl.bat" with following content:

```
@ECHO OFF
wsl dub %*
```

This works great. I am able to use this batch file in IntelliJ. By pressing execute button in IntelliJ, 
a linux binary is created and executed while running IntelliJ on Windows.

I will now check whether I can get GDB working

**Comment by andre2007** [comment]
Thanks for the information. I just wonder because this solution seems rather complex. I do not know the IntelliJ SDK but in almost all languages it is just a flag with which you can enable the shell functionality while executing an OS process. Just as an arbitrary example Python:subprocess.call("mycmd" + " myarg", shell=True)The shell functionality is not limited to this use case. Also it shouldn't hurt in the default case.

**Comment by SingingBush** [comment]
When starting some command line tool there's typically Java code that looks something like:

```Java
final GeneralCommandLine cmd = new GeneralCommandLine()
    .withParentEnvironmentType(GeneralCommandLine.ParentEnvironmentType.CONSOLE)
    .withWorkDirectory("/some/path")
    .withExePath("/path/to/exe")
    .withParameters("arg1", "-also", "another");
```

So if there has been a checkbox ticked for using wsl, I presume the exe would be wsl.exe and the tool and other args will all be in the parameters section.

**Comment by andre2007** [comment]
The solution (dubwsl.bat) works very well. Therefore I close this issue.
