### ISSUE TITLE
Call gdb with correct executable extension (on windows)

### ISSUE THREAD

**Issue by andre2007** [intellij-dlanguage/intellij-dlanguage#424]
On Windows 10 I am using the Windows Sub System for Linux functionality to create linux binaries.

I created a batch file "dubwsl.bat" with content
```
@ECHO OFF
wsl dub %*
```
and a batch file "gdbwsl.bat" with content
```
@ECHO OFF
wsl gdb%*
```

(These two bat files are needed as workaround due to issue https://github.com/intellij-dlanguage/intellij-dlanguage/issues/423)

I set as dub path in IntelliJ the dubwsl.bat file and as gdb path the gdbwsl.bat file.
While I trigger "Run Dub" within IntelliJ the linux binary is created and executed successful.

While trying to start GDB I am facing an issue:

```
20:40:54.230 0> C:\D\tools\gdbwsl.bat --interpreter=mi2
20:40:54.247 1> -break-insert -f C:/D/projects/t1/source/app.d:6
20:40:54.320 2> -list-features
20:40:54.320 3> file C:/D/projects/t1/t1.exe
20:40:54.320 4> run
```

Dub has created the linux file **C:/D/projects/t1/t1** but to GDB the file path with an exe extension is passed. Maybe there is some hard coded extension for windows ".exe". Could you check whether you can instead retrieve the executable file path from dub describe (Which runs on my linux sub system and therefore will return the file path without .exe)

**Comment by bamarc** [comment]
> Dub has created the linux file C:/D/projects/t1/t1 but to GDB the file path with an exe extension is passed. Maybe there is some hard coded extension for windows ".exe"

There actually is. I believe this could easily be fixed by changing this line in `RunUtil`
from

```
if (SdkUtil.isHostOsWindows()) {
                execName = execName.concat(".exe");
        }
```

to 

```
if (SdkUtil.isHostOsWindows()) {
            if (!execName.endsWith(".exe") || !execName.endsWith(".bat")) {
                execName = execName.concat(".exe");
            }
        }
```

**Comment by andre2007** [comment]
Thanks for having a look. While this would solve my specific issue, this solution is very coupled to my bat file scenario. In future maybe the bat file is not necessary anymore and then this solution will break. I think the most future proof solution would be to ask "dub describe" where the executable is located at and with which exact file path.

**Comment by andre2007** [comment]
Solved with https://github.com/intellij-dlanguage/intellij-dlanguage/pull/429.
