### ISSUE TITLE
Some dub options cannot be specified for the run configuraion

### ISSUE THREAD

**Issue by the-Mitu** [intellij-dlanguage/intellij-dlanguage#435]
Some configuration options for dub are not able to be specified in the run configuration. For example I would like to add in a custom registry. A dub should be called as follows:

```
dub build --registry https://cust.om/registry
```

However, currently it cannot be done - run configuration does not give user any option to specify dub arguments apart from the limited set of those that are supported.

I think there should be a textarea to allow users fill in additional dub parameters.

**Comment by andre2007** [comment]
The field you are searching for is the parameters field:

![image](https://user-images.githubusercontent.com/1451047/42594082-68c6c71e-854e-11e8-877f-d35aeb7a215b.png)

**Comment by the-Mitu** [comment]
OK, thank you. I thought these are the runtime parameter for the built
executable. I'll close the issue then.

**Comment by andre2007** [comment]
For your information, you can use this field too for runtime parameters.
The runtime parameters are separated from the dub parameters using a dash pair:

```--arch=x86 -- --run-var1=abc --run-var2=def```

**Comment by the-Mitu** [comment]
Ah, OK. Extremely unintuitive, but I guess there's no better option to do it in dub, as you have to put two argument lists in one :)
