### ISSUE TITLE
IllegalArgumentException: No group with name <threadId>

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#436]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/590888344/

```
IllegalArgumentException: No group with name <threadId>
    at java.util.regex.Matcher.getMatchedGroupIndex(Matcher.java:1316)
    at java.util.regex.Matcher.group(Matcher.java:572)
    at uk.co.cwspencer.gdb.gdbmi.GdbMiParser2.parseVarCreateLine(GdbMiParser2.java:1293)
    at uk.co.cwspencer.gdb.gdbmi.GdbMiParser2.parseImmediateLine(GdbMiParser2.java:725)
    at uk.co.cwspencer.gdb.gdbmi.GdbMiParser2.parseLine(GdbMiParser2.java:569)
...
(5 additional frame(s) were not displayed)

No group with name <threadId>
```

**Comment by andre2007** [comment]
The line GdbMiParser2.java:1293 does neither fit develop or master branch. Are you sure you have the latest state checked out? By looking at the source code I cannot find any bug which could cause the exception. Could you add the content of variable line to this issue?

**Comment by pirocks** [comment]
For me line 1293 on master is:
```
hasMoreVal.value.string = m.group(++matchGroup);
```
This seems to match the stack trace.

**Comment by pirocks** [comment]
gdb version: GNU gdb (mago-mi 0.3.3) 7.1.90
plugin version: 1.17

**Comment by andre2007** [comment]
I replaced the index access of regex groups with name access in this function (branch develop). This makes it easier to have optional groups.

I read the exception (No group with name <threadId>) as: The regex group access with name goes wrong. But maybe I am wrong.

https://github.com/intellij-dlanguage/intellij-dlanguage/blob/develop/src/main/java/uk/co/cwspencer/gdb/gdbmi/GdbMiParser2.java#L1299

In an old state of my code, this error occurred but it should not be possible with the state in branch "develop"

**Comment by pirocks** [comment]
Closing, since this appears resolved.

**Comment by SingingBush** [comment]
closing again, reopened in error
