### ISSUE TITLE
TextBasedThrowable reported

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#439]
https://sentry.io/francis-nixon/intellij-dlang-main/issues/583967593/

```
TextBasedThrowable: None
    at com.intellij.diagnostic.IdeaReportingEvent.<init>(IdeaReportingEvent.java:20)
    at com.intellij.diagnostic.IdeErrorsDialog.a(IdeErrorsDialog.java:597)
    at com.intellij.diagnostic.IdeErrorsDialog.doOKAction(IdeErrorsDialog.java:367)
    at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1869)
    at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1829)
...
(39 additional frame(s) were not displayed)
```

**Comment by pirocks** [comment]
I'm not sure how this happened, I can find no mention of `TextBasedThrowable` in our source.

**Comment by pirocks** [comment]
Additional info: | None
-- | --
App Build | CL-182.3208.14
App Full Name | CLion
App Name | CLion
App Version | 2018.2 EAP
D Format Version | 0.8.1
DCD Client Version | v0.9.8 717023b8b38c0f75687936272f81f274e4728f26
DCD Server Version | v0.9.8 717023b8b38c0f75687936272f81f274e4728f26
DFix Version |  
DScanner Version | v0.5.6
Dub Version | DUB version 1.9.0, built on May  1 2018
GDB Version | GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Is EAP | true
Java version | 1.8.0_152-release
Java vm vendor | JetBrains s.r.o
Last Action | CloseProject
OS Name | Linux
Plugin Id | net.masterthought.dlanguage
Plugin Name | None
Plugin Name FallBack | D Language
Plugin Version | None
Plugin Version Fallback | 1.17-eap734

**Comment by SingingBush** [comment]
TextBasedThrowable is a general exception that get's picked up by the error reporter for numerous things so there isn't enough info here to clearly know what the problem was or how to solve it.

Closing
