### ISSUE TITLE
Installing IntelliJ-DLanguage

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#449]
The README shows v1.7 being installed in 2016. Using IDEA 2018.2 EAP v1.10 (also 2016) is shown. There is no sign of 1.16.2 whcih is the last release.

**Comment by SingingBush** [comment]
if you're running EAP Intellij then you're probably always going to be better of using our [eap builds](https://plugins.jetbrains.com/plugin/8115-d-language). Afaik only JDK8 is supported by Intellij, also CLion support is very much a work in progress. Please report any CLion related issues with full details of steps to recreate along with stacktrace, screenshots, etc.

**Comment by russel** [comment]
I didn't know about the EAP builds. I think that has to be the route for me if only JDK8 is supported; I only have JDK10, so have had to build with that and this might introduce spurious errors that are not worth following up.

Good to see the CLion version: I am convinced it is the platform to target principally just as the Rust plugin now does. However working in IDEA is also a good thing exactly because the Rust plugin does.

I'll use IDEA when I need to do application work, but try CLion at every stage and see if I can do proper reporting back.

**Comment by russel** [comment]
@SingingBush Is is possible to connect to the EAP plugin store directly so as to pickup upgrades automatically or is it a question of download and install for each update?

**Comment by SingingBush** [comment]
it's supposed to be possible through the IDE but I'm not sure on the steps as I've never done it

**Comment by SingingBush** [comment]
v1.17 is now in the [plugin repo](https://plugins.jetbrains.com/plugin/8115) and will support any other Intellij version released this year as well as being the first step towards supporting CLion. It should be able for download soon.
The remaining 1.17 issues have been pushed back to the [1.17.1 milestone](https://github.com/intellij-dlanguage/intellij-dlanguage/milestone/12).
