### ISSUE TITLE
DUB dependencies are not deduplicated

### ISSUE THREAD

**Issue by the-Mitu** [intellij-dlanguage/intellij-dlanguage#451]
Each time D libraries are processed (either by saving dub.json or clicking "Process D libraries), the libraries are added to the IDEA's module depencencies. They are not deduplicated though, so after some time there are loads of copies of the same library listed.

**Comment by andre2007** [comment]
I am not able to reproduce this issue. I am also not sure what do you mean with "IDEA's module dependencies.

Do you mean the external libraries?

![image](https://user-images.githubusercontent.com/1451047/42593802-c7c2818c-854d-11e8-9053-f3729034b7ac.png)

Please add a description how to reproduce the issue and also a screenshot. Which version of the IntelliJ D Language Plugin do you use?

**Comment by SingingBush** [comment]
This was sorted in #416 we just need to get to a point where we can do another release.

**Comment by the-Mitu** [comment]
This is probably a different issue:

- I see multiplicates of **the same** version of every library
- Issue is still present in 1.17

**Comment by pirocks** [comment]
Can you post a screenshot of libraries/your dub.json/sdl?

**Comment by the-Mitu** [comment]
![screenshot_20180719_110655](https://user-images.githubusercontent.com/3919854/42933070-2c5b75d0-8b44-11e8-8320-3f94843901ed.png)

```json
{
	"name": "seg-generator",
	"authors": [
		"Piotrek Mitana"
	],
	"dependencies": {
		"vibe-d:web": "~>0.8.4",
		"vibe-d:tls": "~>0.8.4",
		"seg-generator:geomops": "*",
		"seg-generator:lampplacer": "*",
		"seg-generator:segdata": "*",
		"postgis-d": {
			"path": "./postgis-d"
		},
		"proj4d": {
			"path": "./proj4d"
		}
	},
	"targetType": "executable",
	"license": "proprietary",
	"configurations": [
		{
			"name": "default",
			"excludedSourceFiles": ["src/gui/*"]
		},
		{
			"name": "gui",
			"versions": ["GUI"],
			"excludedSourceFiles": ["src/rest/*"],
			"dependencies": {
				"gtk-d": "~>3.8.2"
			}
		},
		{
			"name": "gui-drawAll",
			"versions": ["GUI", "ShowBothLinestringsAndBeziers"],
			"excludedSourceFiles": ["src/rest/*"],
			"dependencies": {
				"gtk-d": "~>3.8.2"
			}
		},
		{
			"name": "unittest",
			"excludedSourceFiles": ["src/main.d", "src/gui/*"],
			"targetType": "library"
		}
	],
	"subPackages": [
		"./geomops",
		"./lampplacer",
		"./segdata"
	],
	"subConfigurations": {
		"vibe-d:tls": "botan"
	}
}
```

**Comment by SingingBush** [comment]
@the-Mitu have you run _process D libraries_ again? If so, then feel free to reopen the issue

**Comment by the-Mitu** [comment]
@SingingBush, procesing D libraries again fixes the situation.

I'd still recommend to reopen the issue, so that processing dub libraries on saving dub files deduplicated the libraries properly. Currently I'd have to manually trigger processing for each module one after another to fix the library list.

Another thing is that during processing D libaries (either by choosing the option or saving dub file) the entire IDE lags badly - but that possibly needs a separate ticket.

**Comment by SingingBush** [comment]
There's already some work around getting changes to dub project to update automatically. The way the integration currently works is not great, it needs redesigning. It's just taking a while as I have little time at the moment and most things in this plugin need testing manually.
