### ISSUE TITLE
keeps compiling things in the background 

### ISSUE THREAD

**Issue by cyian-1756** [intellij-dlanguage/intellij-dlanguage#456]
Using IC-181.5540.7 and plugin version 1.16.2

DMD version is v2.078.0

Seemly whenever I type anything into IDEA (While on a D project) dmd is called to compile /tmp/dub-build-XXXXXX-XXXX-XXXX-XXXXXXXX.rsp. This happens several times a minute and makes the plugin rather unusable (as it keeps my cpu pegged at 100

**Comment by andre2007** [comment]
This is already fixed. With the next version of the plugin, syntax is checked without generating binaries (DFLAGS -o- is used while calling dub to check the syntax).

**Comment by SingingBush** [comment]
I'll do a release today

**Comment by SingingBush** [comment]
v1.17 is now in the [plugin repo](https://plugins.jetbrains.com/plugin/8115). You should be able to update soon
