### ISSUE TITLE
[get ready for D 2.082's dub] Support for "syntax" build type

### ISSUE THREAD

**Issue by the-Mitu** [intellij-dlanguage/intellij-dlanguage#470]
D 2.082 adds the "syntax" build type to DUB to be used by IDE's - so that the syntax checking can be performed without generating anything. Using it will probably speed up code editing.

More: https://dlang.org/changelog/pending.html#buildTypeSyntax

**Comment by andre2007** [comment]
Behind the new build type "syntax" is the dmd compiler switch "-o-".
This compiler switch is already used in the DLang plugin. The PR was merged some weeks ago https://github.com/intellij-dlanguage/intellij-dlanguage/pull/453. It solved a lot of issues and also speed was improved.

I think this issue can be closed;)
