### ISSUE TITLE
std.Socket.SocketOSException@std\socket.d(2809): Unable to connect socket

### ISSUE THREAD

**Issue by artemirq** [intellij-dlanguage/intellij-dlanguage#471]
Hi!

I just configured Dub and DCD:

![image](https://user-images.githubusercontent.com/17342159/44271503-f5ca0980-a242-11e8-8e2b-0d80b83f4ec4.png)
![image](https://user-images.githubusercontent.com/17342159/44271491-f19dec00-a242-11e8-85fd-aa6719941efe.png)

But this plugin doesn't correctly work with DCD:
1) Very long loading when calling the completion
![image](https://user-images.githubusercontent.com/17342159/44271576-31fd6a00-a243-11e8-93e1-499926ba610a.png)
2) After close IDE appears error message
![image](https://user-images.githubusercontent.com/17342159/44271406-b996a900-a242-11e8-985b-2a6fe6d60bcd.png)

Same problems if:
1) I set path to the libraries for DCD in `Flags`
2) Call Tools -> Process D Libraries

**Comment by andre2007** [comment]
With the most recent version of the plugin it isn't necessary anymore to set the paths to phobos/druntime. The paths which are set on SDK sourcepaths are used. See example here https://user-images.githubusercontent.com/8014057/43798618-cdf89540-9a93-11e8-8c58-2edd7eea780d.png . Please check whether the paths are correct for your system as they are auto detected. Please also check whether you use the latest version of the plugin.

**Comment by artemirq** [comment]
@andre2007 Paths are correctly
https://user-images.githubusercontent.com/17342159/44274291-77716580-a24a-11e8-8ceb-365545ba282f.png
https://user-images.githubusercontent.com/17342159/44274255-632d6880-a24a-11e8-98bf-e62822c3910f.png

Version of plugin `1.17.1`
https://user-images.githubusercontent.com/17342159/44274351-9a9c1500-a24a-11e8-85e6-7fcd1e8e0013.png

**Comment by andre2007** [comment]
For every code completion request a dcd client process is started. Dcd client talks to dcd server using tcp.  By any chances does your anti virus software / firewalls slows downs this process? Could you deactivate both just for testing whether they cause the issue?

**Comment by artemirq** [comment]
@andre2007 I don't use anti-virus software and windows firewall is disabled. [Coedit](https://github.com/BBasile/Coedit) as well works using DCD, but does not have these problems, which have this plugin
https://user-images.githubusercontent.com/17342159/44280360-32a2fa00-a25d-11e8-882c-cb874470c935.png

**Comment by artemirq** [comment]
I noticed, what if i run Coedit, then Intellij Idea - autocomplete [works](https://user-images.githubusercontent.com/17342159/44281079-45b6c980-a25f-11e8-9996-cbba2d5f7f22.png)
It means, what plugin/Idea somehow incorrectly start`dcd-server`

**Comment by andre2007** [comment]
I looked at the source code of dcd client. In case an exception is thrown, this is not catched and is forwarded to druntime, causing the message box you see while closing IntelliJ. https://github.com/dlang-community/DCD/blob/master/src/dcd/common/messages.d#L251 Assumption is, if any of the DCD client calls fails due to an exception, this will block dcd server completely. I will add this info to the issue @SingingBush created at DCD repository. Regarding your assumption, dcd server is called wrong in IntelliJ. Currently the start parameters are not written to the log. This should be changed as it is mandatory for error analyze.

**Comment by artemirq** [comment]
@andre2007 Sounds great. I test it when it's will be available and share the results

**Comment by psycha0s** [comment]
I still get this error window after closing IDEA
![screenshot_2](https://user-images.githubusercontent.com/8014057/52174789-27f80500-27aa-11e9-8d2e-0b5e2067b31c.png)

**Comment by andre2007** [comment]
@psycha0s
There isn't a new release from dcd so far, containing the fix. 
Did you build dcd from master?

**Comment by psycha0s** [comment]
Oh, sorry, I misunderstood. I thought it should be already here.

**Comment by andre2007** [comment]
Hopefully the call of dcd will change completely in future, see here https://github.com/dlang-community/DCD/issues/582

**Comment by andre2007** [comment]
New dcd version is released 
https://github.com/dlang-community/DCD/releases/tag/v0.11.0

**Comment by psycha0s** [comment]
Thanks for the notification!

**Comment by artemirq** [comment]
@andre2007 Thanks. Autocompletion strange works: very slowly and breaks down after I want to get autocompletion for a class

![image](https://user-images.githubusercontent.com/17342159/52591974-50d96380-2e56-11e9-8f40-a0d14040e0f0.png)

`dub 1.13.0`, `DCD 0.11.0`, `DMD32 D Compiler v2.084.1`

**Comment by artemirq** [comment]
@andre2007 Do you use Intellij IDEA with this plugin and DCD for developing? In your case all works is normally? Maybe I wrong with configuration or whatever...
It seems to be, what on VS Code it's better works this...

**Comment by andre2007** [comment]
@artemirq yes, but I deactivated the automatic code completion and use it only from time to time via keyboard shortcut.
In general the way dcd currently works is error prone and slow, see details here https://github.com/dlang-community/DCD/issues/582

I assume you didn't configured it wrong, but a lot of things can go wrong (firewalls, anti virus checks) .
If the dcd communication channel is improved all of this issues disappear and the code completion will be without noticeable delays.

**Comment by artemirq** [comment]
@andre2007 I like how `DLS` works at VS Code plugin. You tried it? If we get [DLS Intellij Idea Plugin](https://github.com/d-language-server/dls/issues/26), many problems will disappear

**Comment by artemirq** [comment]
I close issue, because don't get exceptions while using with new version of `DCD`

**Comment by andre2007** [comment]
I tried to to use DLS (There is a generic language server protocol plugin available) in combination with intellij-dlanguage plugin.
Unfortunately you can't use this combination at the moment. DLS (LSP plugin) stops to work if you one installed intellij-dlanguage plugin.

https://github.com/gtache/intellij-lsp/issues/54
