### ISSUE TITLE
Floating point literals cause "unexpected identifier" errors on the line containing them

### ISSUE THREAD

**Issue by andrejp88** [intellij-dlanguage/intellij-dlanguage#485]
If I write a floating point literal (such as `0f`), a part of the line is underlined in red saying that there is an unexpected identifier.

If the literal is passed as an argument to a function call, the `f` is underlined and the semi-colon is marked as a warning stating that it's an empty statement:  
![](https://i.imgur.com/yjQiCTj.png)

If the literal is part of an assignment, then the variable name on the left hand side is underlined:  
![](https://i.imgur.com/1SisxAd.png)

Removing the `f` works as a workaround in some cases but other times it's required. This doesn't seem to happen with long integer literals (e.g. `0L`) nor does changing it to `0F` fix things.

IntelliJ version:
> IntelliJ IDEA 2018.3.3 (Community Edition)
> Build #IC-183.5153.38, built on January 9, 2019
> JRE: 1.8.0_152-release-1343-b26 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 8.1 6.3

I searched the existing issues but was surprised to not see any mention of this, so I'm worried this may not be easy to reproduce...

**Comment by pirocks** [comment]
Sorry this took so long for me to address. Fix is in develop branch.

**Comment by SingingBush** [comment]
@pirocks I've just been working on the Jenkins build as it was failing to install dub. Now that it's getting past that there are failing _DLanguageParserTest_ tests that were previously ok. Can you take a look as it is probably related to this

**Comment by andrejp88** [comment]
I don't know if this helps, but I've realized that this only occurs for floating point literals without a decimal point (0.0f is fine, 0f is not).

**Comment by andrejp88** [comment]
(Apologies, misread "close and comment" as "close comment")

**Comment by pirocks** [comment]
I've fixed the failing ParserTests , however I was getting failures on other, unrelated tests locally.
