### ISSUE TITLE
Pointless /out/production directory

### ISSUE THREAD

**Issue by the-Mitu** [intellij-dlanguage/intellij-dlanguage#489]
Intellij copies the entire source tree to /out/production directory. Existence of such a directory is justified for Java, for which it contains the .class files. However for D project it either should not be created or should contain *.o/*.obj files instead of copied .d sources.

**Comment by SingingBush** [comment]
Are you using the option to build with DMD? I've only ever used dub and don't recall seeing this.

**Comment by the-Mitu** [comment]
No, I'm building with DUB.

**Comment by andre2007** [comment]
I also see the ```out``` folder in all of my dub projects.
It appears if you create a new dub project and then execute the defaulted "Run Dub" configuration.

**Comment by pirocks** [comment]
This can be prevented by removing Build from this part of the run dub configuration:

![image](https://user-images.githubusercontent.com/10455020/53799693-e38b9080-3f32-11e9-95ee-e49421e08fc4.png)

Not yet sure how to do this programmatically.

**Comment by the-Mitu** [comment]
@pirocks, thank you - the workaround works. Still I believe this is a valid issue and the /.d files in /out/production could possibly be replaced with object files (if turned on).

**Comment by SingingBush** [comment]
in DlangRunDubConfigurationType there is a static class; DLanguageFactory which extends ConfigurationFactory. It seems that by overriding *configureBeforeRunTaskDefaults* it may be possible to prevent the build task.

I suspect one of the following options should be ok but not got the time to test this out at the minute:

```java
    @Override
    public void configureBeforeRunTaskDefaults(Key<? extends BeforeRunTask> providerID, BeforeRunTask task) {
        if(CompileStepBeforeRun.ID.equals(providerID) ) {
            task.setEnabled(false);
        }
    }
```

```java
    @Override
    public void configureBeforeRunTaskDefaults(Key<? extends BeforeRunTask> providerID, BeforeRunTask task) {
        task.setEnabled(false); // should we just disable everything??
    }
```

If someone can help test this out then perhaps it can be fixed quickly.

at the same time it's probably also worth setting the run configuration singleton policy:

```java
    @Override
    public @NotNull RunConfigurationSingletonPolicy getSingletonPolicy() {
        return RunConfigurationSingletonPolicy.SINGLE_INSTANCE_ONLY;
    }
```

**Comment by SingingBush** [comment]
The method mentioned in my previous comment was the solution. This will be in the next release
