### ISSUE TITLE
Add support for GCC.

### ISSUE THREAD

**Issue by RustyRaptor** [intellij-dlanguage/intellij-dlanguage#495]
Congrats to the D community, the D language front-end has been merged into GCC 9.1 recently. 
With that being said it might be a good idea to start adding support for using GCC in intellij-dlanguage.

**Comment by SingingBush** [comment]
There's been an intention to improve how we handle the various D compilers for sometime (#136). At the minute it's a struggle just to keep the plugin working with the features it already has.

Some work has been done to overhaul how the D "sdk"/toolchain is done in Intellij but it's not ready to be pushed.
