### ISSUE TITLE
SDK not setup

### ISSUE THREAD

**Issue by xywf221** [intellij-dlanguage/intellij-dlanguage#501]
#### I was a D novice, I tried to run D's plug-in in ' Clion ', I installed all D tools, but I tried to write code with ' Clion ' but it prompted me not to install the SDK, and my `Clion` version was 2019.1.3

![image](https://user-images.githubusercontent.com/17561378/58681723-38a73900-83a0-11e9-9ff2-ba91007175dc.png)
![image](https://user-images.githubusercontent.com/17561378/58681730-42c93780-83a0-11e9-821a-61cbb5da9839.png)
Please help me, which may cause me to be unable to learn D

**Comment by SingingBush** [comment]
Thanks for raising the issue. The CLion support is still work in progress, some work has been done to handle this but it is incomplete. This problem covered by #464 and #465 so will close this issue as duplicate
