### ISSUE TITLE
question about debugger support under Windows

### ISSUE THREAD

**Issue by 8ctopus** [intellij-dlanguage/intellij-dlanguage#504]
Does the plugin support debugging in the IDE under Windows?

I could find some info about it here [](https://github.com/intellij-dlanguage/intellij-dlanguage/issues/426) but no clear instructions on how to do it.

I've tried downloading magomi (https://github.com/rainers/mago), renaming to gbd.exe and pointing to it from the plugin path but no success.

**Comment by andre2007** [comment]
Yes, see here intellij-dlanguage.github.io
Chapter "debugging"

**Comment by 8ctopus** [comment]
Thank you Andre, I'll try that and sorry for the inconvenience.
