### ISSUE TITLE
Why Java + Kotlin

### ISSUE THREAD

**Issue by andre2007** [intellij-dlanguage/intellij-dlanguage#505]
I am not really familiar with Intellij development but it seems not necessary to have java and kotlin parts in a plugin?

When trying to understand where what is located these separation clearly makes things worse.

Also it blocks contributors because only a small amount knows kotlin. My proposal would be to switch to 1 language,  preferable Java to attract new contributors.

**Comment by SingingBush** [comment]
The intention is for Kotlin to be that one language. There's just no immediate need to convert all the code as Java and Kotlin can co-exist nicely. The CONTRIBUTING.md file does state "new features should ideally be done using Kotlin" but maybe it could be more clear. I doubt that using Kotlin blocks contributors and there's nothing stopping people from committing Java code.

**Comment by andre2007** [comment]
You may misunderstood me. For contributing to an open source project you have at first a learning phase. My gut feeling is, the learning phase is quite high for this plugin:
the code base is split into 2 different directories,  even without this split it is quite hard to get used to the code base. But with this split you have to remember everything twice, check 2 different places, jump from one language to another and back and forward...
I several times tried to get used to the code base but I gave up because the learning effort was just too time consuming.
There are contributors who want help to improve this plugin, but it is really quite hard.

**Comment by SingingBush** [comment]
the learning phase for this project is high. That's always been the case even when it was just Java. It's learning how to work with the intellij platform that's the issue. The documentation that Jetbrains have is getting better though, there was hardly anything when I started trying to help kingsley. 

If I was to start again from scratch I'd use pure Kotlin. That's what Jetbrains seem to be doing with new code and most other plugin projects. I've also had supposedly interested parties asking about the project, that's been driven by the fact that we use Kotlin. Certainly where I'm based there are a lot of long-term Java employers looking for Kotlin experience so I'd expect any Java dev to be keen to take on the challenge.
