### ISSUE TITLE
getBaseDir() deprecation 

### ISSUE THREAD

**Issue by pirocks** [intellij-dlanguage/intellij-dlanguage#508]
`com.intellij.openapi.project.Project#getBaseDir` Is something that we use fairly often in dub code. Generally it gets used to know what directory to find dub.json/dub.sdl in and/or which directory to execute dub in. From the perspective of intellij there is no definition of a project basedir, since projects could have multiple modules all containing various source roots. Ideally we should move to a module based system, and avoid getBaseDir(). However since it is deprecated now should we replace it with `ProjectUtils.guessProjectDir`?

**Comment by SingingBush** [comment]
yeah I think that's the way to go

**Comment by SingingBush** [comment]
Changes done so going to close. Could do with a full regression test but I simply don't have enough time. If any problems arise they can be sorted as new issues.
