### ISSUE TITLE
"Auto Find" button broken -> Trailing whitespace is added

### ISSUE THREAD

**Issue by andre2007** [intellij-dlanguage/intellij-dlanguage#514]
While pressing the "Auto Find" button e.g. on tabstrip "Dub", the dub executable is found but a trailing whitespace is added to the path. This trailing whitespace causing errors like: 

Error running 'Build': Trailing char < > at index 37: C:\Develop\D\dmd2\windows\bin\dub.exe

**Comment by SingingBush** [comment]
Can you pull the changes and check that it's solved for you

**Comment by andre2007** [comment]
Thanks for fixing, it works now.
