### ISSUE TITLE
Do you want to create a project with no SDK assigned?

### ISSUE THREAD

**Issue by Shadowblitz16** [intellij-dlanguage/intellij-dlanguage#517]
I just install this through Intellij Idea and I get this..

![image](https://user-images.githubusercontent.com/2453707/64929323-c422c980-d7d9-11e9-832b-0018f57422a5.png)

going forward eventually shows this message...
```
Do you want to create a project with no SDK assigned?
An SDK is required for compiling, debugging and running applications,
as well as for the standard SDK classes resolution.
```

**Comment by SingingBush** [comment]
There should be an option to select the location of your DMD compiler. The screenshot that's attached doesn't indicate a problem. What's on the following screen?

**Comment by Shadowblitz16** [comment]
there is a configure option but I'm not sure what to selected as it pull up a file menu 
![image](https://user-images.githubusercontent.com/2453707/65176560-d97e3a80-da09-11e9-879c-3e58da553faa.png)

**Comment by Shadowblitz16** [comment]
I figured it out.
seems like it just doesn't load it automatically however when clicking configure I just have to click ok
