### ISSUE TITLE
DUnit: Argument test is missing

### ISSUE THREAD

**Issue by andre2007** [intellij-dlanguage/intellij-dlanguage#518]
Before this line. 

https://github.com/intellij-dlanguage/intellij-dlanguage/blob/5ec1640f4de9ceb81c5a7a0c7ee391095b5a52d7/src/main/java/io/github/intellij/dlanguage/unittest/DUnitTestRunProcessHandler.java#L219

there should be a line
```parametersList.addParametersString("test");```

With this change, d-unit is called correctly, successMatcher is succeeding but still no output is produced to UI. It seems the method testStdOut has no effect?

**Comment by andre2007** [comment]
Second issue is caused by this line:

https://github.com/intellij-dlanguage/intellij-dlanguage/blob/5ec1640f4de9ceb81c5a7a0c7ee391095b5a52d7/src/main/java/io/github/intellij/dlanguage/unittest/DUnitTestRunProcessHandler.java#L153

It must be within the body of ```executeOnPooledThread```. Otherwise the test ends before it is really started.

**Comment by SingingBush** [comment]
Seems weird that _test_ is missing from the command line params. They've not changed in ages. The _testRunFinished()_ method got moved last year because of #432 

I've made the changes. Would you mind pulling develop and making sure it's working as expected. This also means that #432 may become an issue again. If so let me know and I'll take a closer look.

**Comment by andre2007** [comment]
@SingingBush 
I don't know why, but the correction behaves different than in my local correction. While the tests now are executed and you get visual feedback during the test run, after the test, the "Test Results" tree is empty.
As far as I can tell, your coding corrections seems similar like mine.

**Comment by SingingBush** [comment]
ok, let's leave this open then. Can I assign this one to you to continue with?

**Comment by SingingBush** [comment]
This should now be sorted in develop branch.
