### ISSUE TITLE
Jump into D standard Libraries

### ISSUE THREAD

**Issue by kingsleyh** [intellij-dlanguage/intellij-dlanguage#52]
For libraries, you want to call ProjectLibraryTable.getInstance and then get it's modifiable model and add libs there.

I'd recommend searching for uses of that class, and then looking at how it's used. Relevant classes are Library, LibraryTable (and their modifiable models), and then ModifiableRootModel and ModifiableModuleModel for adding roots to modules and modules to the project.

**Comment by pirocks** [comment]
This is now available and working.
