### ISSUE TITLE
Possible memory leak in v1.20.1 in idea 2019.2

### ISSUE THREAD

**Issue by HossainAdnan** [intellij-dlanguage/intellij-dlanguage#522]
Hi, I have been using the community edition for a very small sized project but I can't help but notice that idea quickly takes up over 900MB of memory for a 2/3 tabs within 5~10 minutes and the IDE itself gets unresponsive and sluggish. Is this a possible memory leak? Is there a way to know for sure?

**Comment by SingingBush** [comment]
Are you using D Tools? Please list which ones and the versions. Also which operating system?

**Comment by HossainAdnan** [comment]
yes

dcd-server --version && 
dcd-client --version && 
dfmt --version && 
dscanner --version && 
uname -a

v0.12.0-2-g339d38f
v0.12.0-2-g339d38f
v0.10.1-14-g3f141b2
v0.8.0-7-ga218127
Linux pop-os 5.3.0-19-generic #20-Ubuntu SMP Fri Oct 18 09:04:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


dfix branch v0.3.5

**Comment by pirocks** [comment]
Try allocating about 2 gigs to idea, and seeing if that resolves the problem or only delays it. You can do this in Help > Edit Custom VM Properties, and adding or changing a line to -Xmx2G.

**Comment by SingingBush** [comment]
now that v2.21 has been released, please could you update the plugin and check is this is still an issue? Some changes for both dcd and dub have gone in so it would be good to know if they've helped with this.

**Comment by HossainAdnan** [comment]
Pre-allocating 2GB memory was not helping. However I haven't seen the since the update. Closing.
