### ISSUE TITLE
Develop build known to work on CLion 193 but manual edit of XML file required

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#523]
Changing the line:
```
> git diff src/main/resources/META-INF/plugin.xml
diff --git a/src/main/resources/META-INF/plugin.xml b/src/main/resources/META-INF/plugin.xml
index 429aca17..411fe3e3 100644
--- a/src/main/resources/META-INF/plugin.xml
+++ b/src/main/resources/META-INF/plugin.xml
@@ -55,7 +55,7 @@
     </change-notes>
 
     <!-- please see http://confluence.jetbrains.com/display/IDEADEV/Build+Number+Ranges for description -->
-    <idea-version since-build="192" until-build="192.*"/>
+    <idea-version since-build="192" until-build="193.*"/>
 
     <!-- We want to support IntelliJ IDEA and CLion
         see http://confluence.jetbrains.com/display/IDEADEV/Plugin+Compatibility+with+IntelliJ+Platform+Products
```
causes a good build and the plugin seems to work on CLion 193 (the 2019.3 EAP. Can the change be made in the repository?

**Comment by SingingBush** [comment]
The plugin does not work properly on 2019.3 as many of the tests fail. Simply changing the xml file is not enough to get it 2019.3 ready. See #521

**Comment by SingingBush** [comment]
I had undone the `until-build="193.*"` to be 192.* for the release that was done this morning. Now that the focus is on 2019.3 compatibility I'll put it back to `until-build="193.*"` later today but also update the CI so that the EAP build will have to pass.
