### ISSUE TITLE
Build works with Gradle 5.6.3 but build different target

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#524]
The Gradle wrapper is currently 4.8.1. Gradle is now at 5.6.3. It seems like an update might be in order.

NB Gradle 5 (and I would guess 4) does not work on JDK 13, you have to use JDK 11 or 12.

`./gradlew buildPlugin` builds `build/distribution/intellij-dlanguage-1.21.1-SNAPSHOT.zip`. However, using Gradle 5.6.3 on OpenJDK 11 builds `build/distribution/DLanguage-1.21.1-SNAPSHOT.zip`. The latter is a smaller file than the former.

**Comment by SingingBush** [comment]
I'm open to using Gradle 5 but have not tried it locally yet. The main concern is that it works with the plugins we use. The latest Intellij runs on Java 8 or 11 (Jetbrains own JDK) so there's no need to use later Java versions.

**Comment by SingingBush** [comment]
we're now on 5.6.4: https://github.com/intellij-dlanguage/intellij-dlanguage/commit/54638c8b29ef401a751410c896e7c77e5d8f81fb

may go to Gradle 6
