### ISSUE TITLE
Go to declaration support

### ISSUE THREAD

**Issue by gareth-cross** [intellij-dlanguage/intellij-dlanguage#53]
I have configured dcd-server with the path to my dmd installation headers (`/usr/local/Cellar/dmd/2.069.2/include/d2`). The auto-complete correctly suggests functions from the `std` modules I import. However, IntelliJ's 'go to declaration' and 'go to implementation' functionality does not appear to work.

Is the 'go to' functionality supported yet? If so, how does one enable it? Thanks for developing this plugin.

**Comment by kingsleyh** [comment]
Hi - those functions are not really implemented yet. Currently go to declaration works for some things - mostly Classes and Functions - and find usages works for some things too - but the full references back and forth is still in progress. It's quite a tricky area to get right so I think it will take quite some time of trial and error and experimentation to get it all working - but I'll get there :)

**Comment by kingsleyh** [comment]
Also the DCD config instructions say you should not put the path to the include but to the phobos and druntime/imports here:  https://github.com/Hackerpilot/DCD#configuration-files

**Comment by pirocks** [comment]
This now works.
