### ISSUE TITLE
Create a D SDK with ldc

### ISSUE THREAD

**Issue by bioinfornatics** [intellij-dlanguage/intellij-dlanguage#533]
Dear,
I use `ldc` only for my D projects thus I tried to create a D SDK by providing then a `bin` path to `ldc` executable. But the GUI do not agree with me as a valid D SDK home.

Thanks

**Comment by SingingBush** [comment]
I've been looking at this for some time. It's actually a fairly sizeable piece or work. In the meantime there is a workaround. See #136
