### ISSUE TITLE
display text for vendor url needs changing

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#542]
Jetbrains have asked to change the text on https://plugins.jetbrains.com/plugin/8115 that comes from `plugin.xml`

It should just be a case of changing

```
<vendor url="https://intellij-dlanguage.github.io/">IntelliJ D Language</vendor>
```

to

```
<vendor url="https://intellij-dlanguage.github.io/">D Language</vendor>
```

**Comment by russel** [comment]
I can see why they have asked for the change, and in terms of marketing and branding they have the high ground. As far as I know the Rust plugin just uses the Rust language logo. Perhaps the D plugin can just use the D language logo. Seems like the right brand and marketing approach.
