### ISSUE TITLE
Create a new icon for the project

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#543]
Jetbrains have asked that we change the icon for our project. We'll need to come with some new ideas and create the appropriate png and svg files:

The `intellij-dlang.png` file that is on the main site: https://github.com/intellij-dlanguage/intellij-dlanguage.github.io/blob/master/images/intellij-dlang.png

and the svg version that is here: https://github.com/intellij-dlanguage/intellij-dlanguage/blob/develop/src/main/resources/META-INF/pluginIcon.svg

**Comment by russel** [comment]
I can see why they have asked for the change, and in terms of marketing and branding they have the high ground. As far as I know the Rust plugin just uses the Rust language logo. Perhaps the D plugin can just use the D language logo. Seems like the right brand and marketing approach.

**Comment by SingingBush** [comment]
yeah it's fair enough. It was intended as a homage to Intellij in the same way that the D plugin for VS Code uses a logo similar to Visual Studio. I think until we get something better it'll probably be ok to use:

![dlang](https://user-images.githubusercontent.com/870567/70093973-715af000-1619-11ea-8913-444b8e15291b.png)

**Comment by SingingBush** [comment]
Think it may be best to go with this one

![intellij-dlang](https://user-images.githubusercontent.com/870567/77592012-20814700-6ee9-11ea-97ad-a88e38a14f7a.jpg)

**Comment by SingingBush** [comment]
Changed the web page: https://intellij-dlanguage.github.io/
