### ISSUE TITLE
DMD 2.092 SDK support is broken by deprecation of std.xml

### ISSUE THREAD

**Issue by tsbockman** [intellij-dlanguage/intellij-dlanguage#566]
intelliJ-dlanguage complains that it can't find the `std.xml` module with DMD 2.092. Commenting out the deprecation of `std.xml` in the Phobos source fixes this problem.

**Comment by rikkimax** [comment]
Is this during auto-completion?

**Comment by tsbockman** [comment]
No, it's triggering this error when I try to set Project Structure > Project > Project SDK:

[DLanguage.kt line 100](https://github.com/intellij-dlanguage/intellij-dlanguage/blob/3c5802181d3b7c19741ab20d431d24a8f2d06bf2/src/main/kotlin/io/github/intellij/dlanguage/DLanguage.kt#L100)

**Comment by SingingBush** [comment]
@tsbockman thanks  for raising the ticket and for looking into the cause.

Have you tried using a build off the develop branch since the commit yesterday. If this resolves the issue for you, which it should, I'm happy to do a new release

**Comment by tsbockman** [comment]
This seems to indeed be fixed in 1.24.1.
