### ISSUE TITLE
Compatibility with Ubuntu snaps

### ISSUE THREAD

**Issue by r4j4h** [intellij-dlanguage/intellij-dlanguage#575]
On a newer Ubuntu laptop I found there are "snaps" for DLang provided by https://github.com/dlang-snaps .  They are pretty convenient to install. But they install to non-standard directories, like `/snap/dmd/current/`.

I think this breaks https://github.com/intellij-dlanguage/intellij-dlanguage/blob/develop/src/main/java/io/github/intellij/dlanguage/DlangSdkType.java#L88

I found this because I have an issue identical to https://github.com/intellij-dlanguage/intellij-dlanguage/issues/263 except I use PhpStorm and there is no libraries option.

I think this is not necessarily PhpStorm over IntelliJ because I also saw https://github.com/intellij-dlanguage/intellij-dlanguage/issues/476

I figure this might be a good thing to point out, as since it seems a couple of known paths. are used as a default we may want to expand that list to include the snap directories. It looks like the OP of 476 is not using snaps and is using normal directories, otherwise we might want to include their directories in the list.

This might be fixed inadvertently by using DCD, although PhpStorm's D Tools section has an entry for it. If that entry is not used, it may run into the same path issue. https://github.com/intellij-dlanguage/intellij-dlanguage/pull/339

EDIT: I should add that d-scanner is able to see things fine as far as I can tell manually. Also the IDE is able to see local imports in the project OK it is only external imports like the std library, string, and in my case also dlangui

**Comment by SingingBush** [comment]
sentry report for a _ProcessNotCreatedException_ related to this:

```
Cannot run program "/snap/dmd/dub-v1.22.0-linux-x86_64/dub": error=2, No existe el archivo o el directorio
```

also relates to #550 and #386

**Comment by SingingBush** [comment]
@r4j4h I don't use snaps personally but can you confirm that the following paths will be correct if installing from snapcraft.io:

/snap/dub/current/
/snap/dmd/current/

**Comment by SingingBush** [comment]
Before this ticket can be done completely the paths for phobos and druntime need to be confirmed. I've asked the question on the dmd snap github. This has been a problem for Linux as things get installed all over the place rather that distributions using a common layout. 

As I'm a Fedora user, supporting the official rpm install will always be my priority but I have tried to accomodate Ubuntu and Arch. In #227 there was a table showing paths that we catered for. It's probably a good time to check through these.

System | path | notes
---- | :---- | ----
Windows dmd | C:/D/dmd2/windows/bin/dmd.exe | is there another path for 64-bit? I only have 32bit installed 
Win docs | C:/D/dmd2/html/d
Win phobos | C:/D/dmd2/src/phobos
Win druntime | C:/D/dmd2/src/druntime/import
Mac dmd | /usr/local/opt/dmd | correct for Homebrew but standard maybe '/usr/local/bin'
Mac docs | | not sure
Mac phobos | /Library/D/dmd/src/phobos | not sure if this is standard install or Homebrew
Mac druntime | /Library/D/dmd/src/druntime/import | not sure if this is standard install or Homebrew
Fedora Linux (.rpm) dmd | /usr/bin/dmd
Fedora Linux (.rpm) docs | /usr/share/dmd/html/d
Fedora Linux (.rpm) phobos | /usr/include/dmd/phobos
Fedora Linux (.rpm) druntime | /usr/include/dmd/druntime/import
Ubuntu Linux (.deb) dmd | /usr/local/bin/dmd | *I've not used Ubuntu in ages so would like someone to confirm this*
Ubuntu Linux (.deb) docs | /usr/local/share/dmd/html/d | *I've not used Ubuntu in ages so would like someone to confirm this*
Ubuntu Linux (.deb) phobos | /usr/local/include/dmd/phobos | *I've not used Ubuntu in ages so would like someone to confirm this*
Ubuntu Linux (.deb) druntime | /usr/local/include/dmd/druntime/import | *I've not used Ubuntu in ages so would like someone to confirm this*
Arch Linux dmd | /usr/bin/dmd | same as Fedora (.rpm)
Arch Linux docs | /usr/share/d/html/d | a bit weird
Arch Linux phobos | /usr/include/dlang/dmd | not convinced this is right
Arch Linux druntime | /usr/include/dlang/dmd | not convinced this is right
snapcraft.io dmd | /snap/dmd/current/bin/dmd
snapcraft.io docs | ?? | don't think the snap package adds the docs
snapcraft.io phobos | /snap/phobos/current/import/phobos | Needs Confirmation
snapcraft.io druntime | /snap/druntime/current/import/druntime | Needs Confirmation

**Comment by r4j4h** [comment]
Sorry for the late response, here are my paths:

system | path | notes
-- | -- | --
Ubuntu Linux (.deb) dmd | /snap/bin/dmd  ( also /snap/dmd has docs )  | I've not used Ubuntu in ages so would like someone to confirm this
Ubuntu Linux (.deb) docs | (no html docs as far as i can find) | I've not used Ubuntu in ages so would like someone to confirm this
Ubuntu Linux (.deb) phobos | see below | I've not used Ubuntu in ages so would like someone to confirm this
Ubuntu Linux (.deb) druntime | see below |

phobos might be difficult:
```
jasmine@Genie:~$ sudo find / -name '*phobos*'
/usr/lib/x86_64-linux-gnu/libphobos2-ldc-debug-shared.so.2.0.78
/usr/lib/x86_64-linux-gnu/libphobos2-ldc.a
/usr/lib/x86_64-linux-gnu/libphobos2-ldc-shared.so
/usr/lib/x86_64-linux-gnu/libphobos2-ldc-debug-shared.so
/usr/lib/x86_64-linux-gnu/libphobos2-ldc-debug-shared.so.78
/usr/lib/x86_64-linux-gnu/libphobos2-ldc-shared.so.2.0.78
/usr/lib/x86_64-linux-gnu/libphobos2-ldc-shared.so.78
/usr/lib/x86_64-linux-gnu/libphobos2-ldc-debug.a
/usr/share/lintian/overrides/libphobos2-ldc-shared-dev
/usr/share/doc/libphobos2-ldc-shared-dev
/usr/share/doc/libphobos2-ldc-shared78
/snap/drepl/3/lib64/libphobos2.a
/snap/drepl/3/lib64/libphobos2.so
/snap/drepl/3/lib64/libphobos2.so.0.85
/snap/drepl/3/lib64/libphobos2.so.0.85.1
/snap/dmd/94/import/phobos
/snap/dmd/94/lib64/libphobos2.a
/snap/dmd/94/lib64/libphobos2.so
/snap/dmd/94/lib64/libphobos2.so.0.88
/snap/dmd/94/lib64/libphobos2.so.0.88.1
/snap/dmd/94/phobos-LICENSE.txt
/snap/dmd/25/import/phobos
/snap/dmd/25/lib64/libphobos2.a
/snap/dmd/25/lib64/libphobos2.so
/snap/dmd/25/lib64/libphobos2.so.0.77.1
/snap/dmd/25/phobos-LICENSE.txt
```
druntime easier:
```
jasmine@Genie:~$ sudo find / -name '*druntime*'
/usr/lib/x86_64-linux-gnu/libdruntime-ldc.a
/usr/lib/x86_64-linux-gnu/libdruntime-ldc-debug-shared.so
/usr/lib/x86_64-linux-gnu/libdruntime-ldc-debug-shared.so.78
/usr/lib/x86_64-linux-gnu/libdruntime-ldc-shared.so
/usr/lib/x86_64-linux-gnu/libdruntime-ldc-debug-shared.so.2.0.78
/usr/lib/x86_64-linux-gnu/libdruntime-ldc-debug.a
/usr/lib/x86_64-linux-gnu/libdruntime-ldc-shared.so.78
/usr/lib/x86_64-linux-gnu/libdruntime-ldc-shared.so.2.0.78
/snap/dmd/94/druntime-LICENSE.txt
/snap/dmd/94/import/druntime
/snap/dmd/25/druntime-LICENSE.txt
/snap/dmd/25/import/druntime
```

if it helps here also is my dmd output from find:
```
/snap/bin/dmd.rdmd
/snap/bin/dmd.ddemangle
/snap/bin/dmd
/snap/bin/rdmd
/snap/bin/dmd.dustmite
/snap/dmd
/snap/dmd/94/bin/dmd
/snap/dmd/94/bin/dmd.conf
/snap/dmd/94/bin/rdmd
/snap/dmd/94/command-dmd.wrapper
/snap/dmd/94/command-rdmd.wrapper
/snap/dmd/94/dmd-boostlicense.txt
/snap/dmd/94/man/man5/dmd.conf.5
/snap/dmd/25/bin/dmd
/snap/dmd/25/bin/dmd.conf
/snap/dmd/25/bin/rdmd
/snap/dmd/25/command-dmd.wrapper
/snap/dmd/25/command-rdmd.wrapper
/snap/dmd/25/dmd-boostlicense.txt
/snap/dmd/25/man/man1/dmd.1
/snap/dmd/25/man/man5/dmd.conf.5
```
and here is some further analysis, indicating /snap/dmd/current/ is a good starting point
```
jasmine@Genie:/snap/dmd$ ls -lha /usr/lib/x86_64-linux-gnu/libdruntime-ldc.a
-rw-r--r-- 1 root root 3.3M Mar 12  2018 /usr/lib/x86_64-linux-gnu/libdruntime-ldc.a
jasmine@Genie:/snap/dmd$ ls -lha /snap/bin/dmd
lrwxrwxrwx 1 root root 13 Jun 18 18:22 /snap/bin/dmd -> /usr/bin/snap
jasmine@Genie:/snap/dmd$ ls -lha /usr/bin/snap
-rwxr-xr-x 1 root root 17M Sep  4 08:42 /usr/bin/snap
jasmine@Genie:/snap/dmd$ ls -lha /snap/bin/rdmd
lrwxrwxrwx 1 root root 8 Jun 18 18:22 /snap/bin/rdmd -> dmd.rdmd
jasmine@Genie:/snap/dmd$ ls -lha /snap/dmd
total 8.0K
drwxr-xr-x  4 root root 4.0K Jun 18 18:22 .
drwxr-xr-x 19 root root 4.0K Jun 18 17:48 ..
drwxr-xr-x  8 root root  302 Feb  3  2018 25
drwxr-xr-x  9 root root  325 Dec  7  2019 94
lrwxrwxrwx  1 root root    2 Jun 18 18:22 current -> 94
```
And here is how I got to final paths:
```
jasmine@Genie:/snap/dmd$ ls -lha /snap/dmd/current/
total 11K
drwxr-xr-x 9 root root  325 Dec  7  2019 .
drwxr-xr-x 4 root root 4.0K Jun 18 18:22 ..
drwxr-xr-x 2 root root   87 Dec  7  2019 bin
-rwxr-xr-x 1 root root   42 Dec  7  2019 command-ddemangle.wrapper
-rwxr-xr-x 1 root root   36 Dec  7  2019 command-dmd.wrapper
-rwxr-xr-x 1 root root   41 Dec  7  2019 command-dustmite.wrapper
-rwxr-xr-x 1 root root   37 Dec  7  2019 command-rdmd.wrapper
-rw-r--r-- 1 root root 1.4K Dec  7  2019 dmd-boostlicense.txt
drwxr-xr-x 2 root root   30 Dec  7  2019 doc
-rw-r--r-- 1 root root 1.4K Dec  7  2019 druntime-LICENSE.txt
drwxr-xr-x 4 root root   45 Dec  7  2019 import
drwxr-xr-x 2 root root  122 Dec  7  2019 lib64
drwxr-xr-x 4 root root   39 Dec  7  2019 man
drwxr-xr-x 3 root root   43 Dec  7  2019 meta
-rw-r--r-- 1 root root 1.4K Dec  7  2019 phobos-LICENSE.txt
drwxr-xr-x 2 root root   58 Dec  7  2019 snap
jasmine@Genie:/snap/dmd$ ls -lha /snap/dmd/current/bin
total 19M
drwxr-xr-x 2 root root   87 Dec  7  2019 .
drwxr-xr-x 9 root root  325 Dec  7  2019 ..
-rwxr-xr-x 1 root root 2.5M Dec  7  2019 ddemangle
-rwxr-xr-x 1 root root 7.6M Dec  7  2019 dmd
-rw-r--r-- 1 root root  335 Dec  7  2019 dmd.conf
-rwxr-xr-x 1 root root 4.4M Dec  7  2019 dustmite
-rwxr-xr-x 1 root root 3.7M Dec  7  2019 rdmd
jasmine@Genie:/snap/dmd$ ls -lha /snap/dmd/current/import/
total 0
drwxr-xr-x 4 root root  45 Dec  7  2019 .
drwxr-xr-x 9 root root 325 Dec  7  2019 ..
drwxr-xr-x 4 root root  66 Dec  7  2019 druntime
drwxr-xr-x 4 root root  37 Dec  7  2019 phobos
jasmine@Genie:/snap/dmd$ ls -lha /snap/dmd/current/import/phobos/
total 0
drwxr-xr-x  4 root root  37 Dec  7  2019 .
drwxr-xr-x  4 root root  45 Dec  7  2019 ..
drwxr-xr-x  3 root root  24 Dec  7  2019 etc
drwxr-xr-x 12 root root 910 Dec  7  2019 std
```
So the phobos and druntime imports don't match up with a clean import folder. What does /import look like on the other systems? Hope that helps you locate what you need but let me know if you would like to see more (or for me to update again lol this laptop hasn't been run in a while)
