### ISSUE TITLE
Possibly undefined symbol for .length

### ISSUE THREAD

**Issue by azihassan** [intellij-dlanguage/intellij-dlanguage#587]
**Desktop (please provide environment info):**
 - OS: Ubuntu 18.04 64 bits
 - IDE: Intellij 2020.2
 - Plugin Version 1.25

**D compiler and tools (please provide version numbers):**
 - dmd: 2.093.0
 - dub: 1.22.0
 - dcd: 0.13.1
 - dscanner: 0.10.0-3-g2a1f96f

**Describe the problem**
I'm getting a "Possibly undefined symbol" warning for the .length property.

```d
void main(string[] args)
{
    args.length.writeln;
}
```

**Screenshots**
![2020-08-18-200042_1366x744_scrot](https://user-images.githubusercontent.com/1638227/90554314-91bde100-e18d-11ea-90ba-30058f9bc392.png)

DCD configuration:
![2020-08-18-200200_1026x744_scrot](https://user-images.githubusercontent.com/1638227/90554416-b914ae00-e18d-11ea-82a9-cdcee4b85d8f.png)

**Additional context**
Autocompletion works for .length, but the warning is still present.

**Comment by SingingBush** [comment]
The way to setup the plugin is just to ensure that phobos and druntime are being picked up as sourcepaths when you select DMD as an sdk:

![intellij-dlang-setup-phobos-and-druntime](https://user-images.githubusercontent.com/870567/95678338-f3b22a00-0bc3-11eb-8e2b-84525db21830.png)

so you're getting auto completion because DCD is aware of phobos/druntime but the plugin itself has not picked those paths up. Also, if they're configured as sourcepaths you will not need to add them as flags to DCD.

**Comment by azihassan** [comment]
Thanks for the reply. I checked the SDK settings and it turns out that the paths are indeed defined :

![image](https://user-images.githubusercontent.com/1638227/96371681-c7b21e00-115a-11eb-9c4d-54bdc71ac980.png)

But the problem persists. I also tried removing the flags from DCD, rebuilding, restarting Intellij. Am I missing someting ?

**Comment by tsbockman** [comment]
> so you're getting auto completion because DCD is aware of phobos/druntime but the plugin itself has not picked those paths up. Also, if they're configured as sourcepaths you will not need to add them as flags to DCD.

The `.length` property of built-in slices is not from druntime or phobos; it is a language feature. Check out these sections in the spec: [Array Properties](https://dlang.org/spec/arrays.html#array-properties) and [Properties](https://dlang.org/spec/property.html).

Similarly, there are also some unrecognized `__traits`, like `identifier`; see [Traits](https://dlang.org/spec/traits.html).

**Comment by therealbluepandabear** [comment]
Just wanted to mention I had an issue in which I got an undefined symbol for everything and I had to permanently disable that inspection as it just wasn't working properly.
