### ISSUE TITLE
Always parses `body` as keyword

### ISSUE THREAD

**Issue by drathier** [intellij-dlanguage/intellij-dlanguage#601]
**Desktop (please provide environment info):**
 - OS: macos 10.15.7
 - IDE: PyCharm 2020.2 and IntelliJ 2020.2
 - Plugin Version 1.25

**D compiler and tools (please provide version numbers):**
 - dmd: DMD64 D Compiler v2.094.1
 - dub: DUB version 1.23.0, built on Oct  2 2020
 - dcd: none
 - dscanner: v0.11.0

**Describe the problem**
The parser always parses the word `body` as a keyword even when it isn't. 

**Please provide full details to reproduce the problem**
```
struct T {
  int body;
}
```

**Screenshots**
<img width="259" alt="Skärmavbild 2020-11-15 kl  18 18 05" src="https://user-images.githubusercontent.com/3695812/99191752-fa0d6600-276e-11eb-8d99-2ae60f815b55.png">

**Comment by SingingBush** [comment]
According to https://dlang.org/spec/lex.html#keywords, _body_ is a keyword. Although it has a strikethrough to mark it as deprecated. This will be resolved in the next release thanks to #666
