### ISSUE TITLE
Support latest IntelliJ

### ISSUE THREAD

**Issue by Imperatorn** [intellij-dlanguage/intellij-dlanguage#606]
**Desktop**
 - OS: Windows 10
 - IDE: Intellij 2020.3
 - Plugin Version: 1.25.1

**D compiler and tools (please provide version numbers):**
 - dmd: 2.096.0
 
**Describe the problem**
In the latest IntelliJ, D language cannot be found in the marketplace and cannot be installed from disk

![image](https://user-images.githubusercontent.com/57035049/111495973-272f4c80-8740-11eb-85af-053ebf159b1a.png)

**Comment by SingingBush** [comment]
changes done in #602
