### ISSUE TITLE
Unnecessary warning - Function return value is discarded

### ISSUE THREAD

**Issue by GavinGrayCT** [intellij-dlanguage/intellij-dlanguage#610]
**Desktop (please provide environment info):**
 - OS: UBUNTU 20.10
 - IDE: IntelliJ IDEA 2020.3.3 (Ultimate Edition)
Build #IU-203.7717.56, built on March 15, 2021
Licensed to ...
 - Plugin Version 1.26

**D compiler and tools (please provide version numbers):**
 - dmd: DMD64 D Compiler v2.096.0
 - dub: DUB version 1.23.0
 - dcd: client and server: v0.13.1-2-gf38d36a
 - dscanner: 
 - etc

**Describe the problem**
With the following code:
    **scope(exit) wait(pipes.pid);**
The IDE warns:
   **Function return value is discarded**

**Please provide full details to reproduce the problem**
Simply have code along the line of:
   auto pid= spawnProcess([runXyz, ipAddress, "6875"]);
   scope(exit) wait( pid);
And the IDE issues the warning.

**Screenshots**

**Additional context**

**Comment by SingingBush** [comment]
that message will be coming from dcd. The intellij plugin just surfaces the information to the UI
