### ISSUE TITLE
Performance issues with the formatting model

### ISSUE THREAD

**Issue by JEphron** [intellij-dlanguage/intellij-dlanguage#611]
I've started using this plugin recently and have been experiencing very high keyboard input latency, specifically when hitting the return key to insert a new line. I've been investigating and the majority appears to come from `io.github.intellij.dlanguage.features.formatter.DFormattingModelBuilder.DFormattingBlock#getSpacing`, which runs many times whenever a newline is inserted. The culprit is `PsiTreeUtil.hasErrorElements` which takes a few milliseconds per call, but since the method is called repeatedly it results in nearly 80ms of added latency, enough to make IntelliJ feel sluggish. 

I'm not sure we need to be checking for valid syntax before formatting. I've looked at a bunch of other IntelliJ plugins with custom formatter implementations and they don't appear to try to validate at that stage. If you have a syntax error, the formatter will indeed mess up the spacing, but as soon as you fix your code and re-run the formatter then the spacing should be fixed. In fact, that's how the official Jetbrains Kotlin formatter works. 

I've also noticed that we have some tests for formatting, but they appear to be mostly commented out. Is that something that'd be worth re-enabling? 

Willing to submit a PR to remove the `hasErrorElements` check, but wanted to bring it up here in case anyone wants to discuss.

**Comment by SingingBush** [comment]
Thanks for looking into it. Sounds like it's worth making the change. I've not looked at `DFormattingModelBuilder.kt` in detail. perhaps @pirocks can provide some detail. I also noticed many of the tests in `DFormatterTest` were commented out back in 2017. I'd welcome a pull request, especially if you are able to help getting the tests back in order
