### ISSUE TITLE
Formatter indentation issues

### ISSUE THREAD

**Issue by JEphron** [intellij-dlanguage/intellij-dlanguage#619]
There are some cases where the formatter doesn't indent multi-line statements.
I think the following cover most of the unexpected behaviors I've encountered

* functions with arguments broken over multiple lines, like
```d
void foo(
string a, 
string b
) {}
``` 
* array literals spanning multiple lines
```d
int[] a = [
1,
2,
3,
];
```

* function calls spanning multiple lines

```d
void foo() {
    bar(1,
    2);    
}
```

* chains of function calls

```d
abc.filter!(...)
.map!(...)
.array;
```

**Comment by SingingBush** [comment]
This will need fixing in _io.github.intellij.dlanguage.features.formatter.DFormattingModelBuilder_ and testing in _io.github.intellij.dlanguage.formatting.DFormatterTest_
