### ISSUE TITLE
The plug-in cannot be used on the latest idea/clion.

### ISSUE THREAD

**Issue by fenginsc** [intellij-dlanguage/intellij-dlanguage#630]
**Desktop (please provide environment info):**
 - OS: windows10 x64
 - IDE: idea 2021.2/clion 2021.2
 - Plugin 1.26.1

**D compiler and tools (please provide version numbers):**
 - dmd: 2.097.2
 - dub: 1.26.1
 - dcd: 0.13.6
 - dscanner:  0.11.1
 - etc

**Describe the problem**
Code completion cannot be used, can’t jump to method definition, can’t even start project on Clion.

**Please provide full details to reproduce the problem**
On IDEA, you cannot use the code hint function, and you cannot hold down the CTRL key and click the method to jump to the method definition, but you can start the project.
On Clion, you cannot use the code hint function, and you cannot press the CTRL key to click the method to jump to the method definition, and even start the project will fail.

**Screenshots**

**Additional context**

**Comment by SingingBush** [comment]
Thanks for raising the issue. The Intellij SDK seems to change too rapidly to keep up recently. Compatibility with 2021.2 is on my radar but the changes to Intellij are happening faster than I have to to address at the moment.
 
CLion support is very much experimental as there are a few [CLion specific issues](https://github.com/intellij-dlanguage/intellij-dlanguage/issues?q=is%3Aissue+is%3Aopen+label%3AClion) that need resolving. Before those problems can be addressed though, these [high priority bugs](https://github.com/intellij-dlanguage/intellij-dlanguage/issues?q=is%3Aissue+is%3Aopen+label%3A%22top+priority%22) need fixing and I've not had time to work on this project recently.
