### ISSUE TITLE
move the intellij-dub plugin code into a sub-module of this repo

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#637]
The additional intellij-dub plugin was created before this codebase was split into modules. Having the separation in terms of code has been good but it's tricky maintaining it as a completely separate plugin with it's own releases and codebase. It also seems that recent changes in Intellij are making it harder to have intellij-dub rely on classes from the main repo.

Before putting the dub code into the project the following packages should probably be put into a core

```
io.github.intellij.dlanguage.icons.DlangIcons
io.github.intellij.dlanguage.module.DlangModuleType
```

These ones are already in *utils* so can either remain there or move into the new *core* module

```
io.github.intellij.dlanguage.messagebus.DubChangeNotifier
io.github.intellij.dlanguage.messagebus.ToolChangeListener
io.github.intellij.dlanguage.messagebus.Topics
io.github.intellij.dlanguage.settings.ToolKey
io.github.intellij.dlanguage.settings.ToolSettings
```

leaving these to either but put into the new *dub* module or reworked (ProcessDLibs could be rejigged)

```
io.github.intellij.dlanguage.project.DubConfigurationParser
io.github.intellij.dlanguage.project.DubPackage
io.github.intellij.dlanguage.run.DlangRunDubConfiguration
io.github.intellij.dlanguage.actions.ProcessDLibs
```

**Comment by rikkimax** [comment]
So this is the first time I've heard of this extra plugin (which isn't a good sign in itself).

And once installed it ugh didn't like the configurations or sub-packages at all (so not much use). So this may support the argument that it should merge into the main plugin.

**Comment by SingingBush** [comment]
It didn't get promoted as it's very much work in progress. Dub support to some extent was already baked into this project and the separate plugin was an attempt to start building out a tool window similar to the Maven/Gradle tool window that can be used to trigger common dub tasks. Pulling it in will almost certainly help to get it moving in the right direction.

**Comment by etienne02** [comment]
It’s possible with ExtensionPoints, to make a plugin provide class for another plugin to extends it.
Do you want to:

1. Merge this plugin into a submodule but keep it a separate plugin
2. Merge the plugin into a submodule but integrate it into this plugin

**Comment by SingingBush** [comment]
I'm happy to merge as-is if you want. Was mainly pointing out that there's value in sdl support outside of a D plugin and was wondering if this was something you'd be interested in doing. Perhaps for now we just merge as it is. If at a later date there's a desire to release it independently we can just pull it out into a separate repo.

**Comment by SingingBush** [comment]
deleted last comment as just realised I posted on wrong thing

**Comment by etienne02** [comment]
I think we can (once, this one is done) even go further and move all dub code related into the new submodule

**Comment by SingingBush** [comment]
yeah definitely. In an ideal world, probably if there were enough people working on it, the code base should be done in a way that a [standalone IDE](https://www.jetbrains.com/help/mps/building-standalone-ides-for-your-languages.html) could be built by using the base open source Intellij with plugins for _dlanguage_, _sdl_, [dub](https://github.com/intellij-dlanguage/intellij-dub), [diet](https://github.com/intellij-dlanguage/intellij-diet). That was the idea behind trying to keep them decoupled where possible.
