### ISSUE TITLE
Restart DCD Server action is disabled

### ISSUE THREAD

**Issue by iamtakingiteasy** [intellij-dlanguage/intellij-dlanguage#647]
**Desktop (please provide environment info):**
 - OS: Archlinux (rolling release, as of 2021-11-30)
 - IDE: IntellijU 2021.2.3
 - Plugin Version 1.26.2

**D compiler and tools (please provide version numbers):**
 - dmd: v2.098.0
 - dub: 1.27.0
 - dcd: v0.13.6
 - dscanner: v0.11.1

**Describe the problem**
"Restart DCD Server" Action and menu item is always disabled/inactive. dcd-server may start once project is opened for first time, but there is no way to restart it from IDE, in case it crashes, freezes or killed.

**Please provide full details to reproduce the problem**
Open a dub project.
Observe DCD Server started.
Try to invoke "Restart DCD Server" action either in DCD server status bar, or from Tools menu.
Both are disabled, unclickable.
Kill dcd-server.
Obseve "Restart DCD Server" as still disabled.

**Screenshots**
After openning the project
![after open](https://public.eientei.org/data/2611304a81d4f0dad944eaa99d1a4047.png)

After killing dcd-server manually
![after killed](https://public.eientei.org/data/8c4639837a61d56fdcd87a058704880f.png)

**Additional context**
-

**Comment by SingingBush** [comment]
please check that dmd is configured properly, perhaps by setting up dmd again and checking that it locates druntime and phobos.

**Comment by iamtakingiteasy** [comment]
Setting DMD SDK: /usr/bin -> locates `DMD64 D Compiler v2.098.0` and sourcepath `/usr/include/dlang/dmd` as per libphobos+druntime arch package https://archlinux.org/packages/community/x86_64/libphobos/ ; The state of "Restart DCD Server" does not change, not after retried setup, nor after IDE restart.

**Comment by iamtakingiteasy** [comment]
After also re-creating a project with dub and importing it with Idea, issue was resolved.

**Comment by SingingBush** [comment]
when you opened the project before did you open it by importing dub.json or opening the root directory? From the original screenshots I can see that the _source_ folder is not marked as a source root, so it possibly is due to how the project was brought into Intellij.

**Comment by iamtakingiteasy** [comment]
It may indeed be related to first use of intellij-dlanguage plugin, when none of the tools was set up. Now however even trying it from another user does not reproduce the issue. Possibly it has to do with remaining configuration of attempts to use the plugin with clion, I had't as much success with clion as even running the dcd-server at all.

**Comment by SingingBush** [comment]
CLion support still needs a ton of work
