### ISSUE TITLE
Support for CLion 2021.3 

### ISSUE THREAD

**Issue by d-static** [intellij-dlanguage/intellij-dlanguage#649]
This is a suggestion. Please add support for CLion 2021.3. This would be awesome.

**Comment by SingingBush** [comment]
Support for 2021.3.* based IDE's should be in _develop_ branch already. I'll try to get a release out soon but in the meantime you could run `./gradlew buildPlugin` from the root of the project in develop. 

Note that there are numerous CLion specific issues that need sorting which can be viewed using the label: https://github.com/intellij-dlanguage/intellij-dlanguage/issues?q=is%3Aissue+is%3Aopen+label%3AClion

**Comment by d-static** [comment]
Thank you.
