### ISSUE TITLE
Execution failed for task ':debugger:instrumentCode'.

### ISSUE THREAD

**Issue by JintaoXIAO** [intellij-dlanguage/intellij-dlanguage#652]
my environment:
**gradle --version**
Initialized native services in: /home/jintao/.gradle/native

Gradle 6.8.3

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.13 (Microsoft 11.0.13+8-LTS)
OS:           Linux 5.13.0-22-generic amd64

--------------------------------------------------------------

command executed:  "**gradle buildPlugin -i**",
error: 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':debugger:instrumentCode'.
> /home/jintao/.sdkman/candidates/java/11.0.13-ms/Packages does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by SingingBush** [comment]
I've not tried with Microsoft JVM but that should be ok as long as it's Java 11. Using the right Gradle version is important though so use the supplied gradle wrapper instead of your systems gradle. You should run `./gradlew buildPlugin`

**Comment by JintaoXIAO** [comment]
@SingingBush 
Sure, I  changed my local Gradle to be the same version as this project's.
when executing with `./gradlew buildPlugin`, just got the same error.
below is my "gradle version" (run by "./gradlew --version"
-----------------------------
➜  intellij-dlanguage git:(develop) ✗ ./gradlew --version
Initialized native services in: /home/jintao/.gradle/native

------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.13 (Microsoft 11.0.13+8-LTS)
OS:           Linux 5.13.0-22-generic amd64

**Comment by SingingBush** [comment]
Can you try OpenJDK. The error does indicate that it's something about the jdk path, not sure what that _Packages_ directory is about. I'd expect your jdk to have directories for bin, lib, include

**Comment by SingingBush** [comment]
Closing as I presume this has been fixed by using an alternative JDK. If it's still a problem feel free to reopen the issue

**Comment by Lonami** [comment]
Had the same issue but in my case it seems creating an empty `Packages` folder (my path being `C:\Program Files\Microsoft\jdk-17.0.1.12-hotspot\Packages`) solved it 🤷‍♀️
