### ISSUE TITLE
use JaCoCo instead of cobertura for test coverage (cobertura is broken on Gradle 7)

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#687]
The gradle-cobertura-plugin doesn't work with Gradle 7 and cobertura isn't being actively maintained. I raised https://github.com/stevesaliman/gradle-cobertura-plugin/pull/178 to at least get the plugin working but it seems that it may not get merged either. 

For now I'm going to disable the coverage workflow. If a new version of gradle-cobertura-plugin is published then I'll re-enable it, alternatively can move to using [JaCoCo](https://docs.gradle.org/current/userguide/jacoco_plugin.html)

**Comment by SingingBush** [comment]
Finally got round to taking a look at this. Settled on using [coveralls-jacoco-gradle-plugin](https://github.com/nbaztec/coveralls-jacoco-gradle-plugin) and Gradle's [jacoco-report-aggregation](https://docs.gradle.org/current/userguide/jacoco_report_aggregation_plugin.html).

Then it's pretty much just a case of putting some config into _build.gradle_ and updating the _coverage.yml_ github action to do:

```
./gradlew jacocoTestCoverageVerification coverallsJacoco
```

**Comment by etienne02** [comment]
We can also use [kover](https://github.com/Kotlin/kotlinx-kover) as we are using more and more kotlin
