### ISSUE TITLE
Named imports symbols are missconsidered in resolve

### ISSUE THREAD

**Issue by etienne02** [intellij-dlanguage/intellij-dlanguage#734]
**Describe the problem**
```D
void main() {
    import std.stdio: wr = writeln;
    wr("test");
    writeln("foo");
}
```
In the previous example, currently `wr` resolve to nothing and is marked as "possible undefined symbol" as `writeln` resolve to the writeln in the import.
It should be the inverse, `wr` call resolve and `writeln` call not.

**Screenshots**
![image](https://user-images.githubusercontent.com/9578950/176318918-681c8bbc-cf6d-4bd5-86ed-6e56481aeb6f.png)

**Comment by SingingBush** [comment]
shouldn't they both resolve to std.stdio.writeln

**Comment by etienne02** [comment]
yes and no, wr should be resolved to std.stdio.writeln (through his alias wr) but writeln is not accessible in this scope because the import introduced the symbol wr and not writeln
