### ISSUE TITLE
inconsistent syntax highlighting (grammar issues)

### ISSUE THREAD

**Issue by kingsleyh** [intellij-dlanguage/intellij-dlanguage#74]
some parts of the grammar look a bit confused around declaration vs statements - the syntax highlighting shows this along with various other inconsistent syntax highlighting

**Comment by Hackerpilot** [comment]
Confusion about declarations vs statements is what D's grammar is all about.

**Comment by pirocks** [comment]
This is no longer an issue with the new parser. Close?
