### ISSUE TITLE
Support for Arch linux D packages

### ISSUE THREAD

**Issue by MightyPork** [intellij-dlanguage/intellij-dlanguage#743]
The standard D library on Arch linux is packaged here:

**libphobos** (dependency of dmd) - https://archlinux.org/packages/community/x86_64/libphobos/

-> /usr/include/dlang/dmd/

This DMD version of the library does not work with the plugin, even when I manually specified it in the classpath. It's odd, since the plugin uses DMD.

there's another one:

**liblphobos** (dependency of ldc) - https://archlinux.org/packages/community/x86_64/liblphobos/

-> /usr/include/dlang/ldc/

This one *works* when manually specified in classpath, but is not automatically found either.

The tools are not initially found either, but the "Auto find" button works, you just have to click all of them in the IDE settings.

**Comment by SingingBush** [comment]
I've taken a closer look at the Arch packages. To be frank, it seems that the Arch package maintainers should have used paths similar to either Fedora or Ubuntu.

For phobos:

Fedora uses `/usr/include/dmd/phobos`  (contains directories for `etc` and `std`)
Ubuntu uses `/usr/local/include/dmd/phobos`  (contains directories for `etc` and `std`)

For druntime:

Fedora uses `/usr/include/dmd/druntime/import` (contains `importc.h` and `object.d`)
Ubuntu uses `/usr/local/include/dmd/druntime/import` (contains `importc.h` and `object.d`)

Not only does Arch add an extra _dlang_ directory into the paths but it also puts phobos and druntime into the same directory:

phobos: `/usr/include/dlang/dmd/`  (contains directories for `etc` and `std`)
druntime: `/usr/include/dlang/dmd/` (contains `importc.h` and `object.d`)

This is unlike any other installation type I've looked at. We already cover Windows, Mac, Ubuntu (.deb), Fedora (.rpm), and snap packages. So Arch is definitely the odd one out.

I'll update the code in question to workaround Arch's use off non-standard paths but really this should be sorted on their end.

Note that these paths end up being used as source paths automatically so there should not be a need to configure dmd. There is no need to setup a classpath either. If phobos and druntime are not detected setting them as sourcepaths manually should be fine:
![image](https://user-images.githubusercontent.com/870567/178103834-0afe2908-0ad8-4bf5-a4cb-7ad60f502115.png)

We do not support LDC being used in the way you have but it seems reasonable that configuring paths for ldc may work fine.

After I've pushed changes would you be able to checkout the develop branch and run the project from source using `./gradlew runIde` to test?

**Comment by SingingBush** [comment]
I took a look at the code in question and it appears that we already check for the path used in Arch:
https://github.com/intellij-dlanguage/intellij-dlanguage/blob/a4f627a64f8982e32c9b29bf9b2aaf58311c8b0c/src/main/java/io/github/intellij/dlanguage/DlangSdkType.java#L99

Interestingly it looks like we've had an Arch user experience problems before. I stated back in 2019 that the Arch package should be fixed:

> If the arch package put's them under /usr/include/dlang/dmd we could consider checking for the existence of that path. I really think that the arch package should be changed to be in line with what the official package would do, perhaps someone who uses arch a lot can look into that: https://www.archlinux.org/packages/community/x86_64/dmd/

see [here](https://github.com/intellij-dlanguage/intellij-dlanguage/issues/457#issuecomment-452628434)

That was more specifically because the non-standard package structure caused problems for DCD.

**Comment by MightyPork** [comment]
I think I can figure out how to run the changed version for a test, when theres' something to try.

I now tried just adding `/usr/include/dlang/dmd` to sourcepath, without `/usr/include/dlang/ldc` in classpath. It didn't work:

![Screenshot_20220709_150604](https://user-images.githubusercontent.com/2041118/178107096-f5825f29-7de3-4ab9-a8a5-fb10509ed6db.png)

object.d is right there in the folder though:

![Screenshot_20220709_150633](https://user-images.githubusercontent.com/2041118/178107113-353e09a0-a45e-4bf5-8ce5-10f7fa8d731d.png)

**Comment by SingingBush** [comment]
although not Arch specific I suspect https://github.com/intellij-dlanguage/intellij-dlanguage/commit/aa88cd0ed9a96b17d4dd08c787e9fcd42807516d will help checking for phobos and druntime correctly (I assume you are using dmd 2.100). It should at least ensure more accurate error messages. 

Please pull the changes on develop and run `./gradlew runIde` with JDK 17

**Comment by MightyPork** [comment]
Ok, I tried that, it works well now, at least regarding this issue.

It indexed `/usr/include/dlang/dmd` and even built and run the app.

the built-in terminal did not show any output until the app ended (i used readf), that's probably an unrelated bug, or maybe an idea bug

**Comment by SingingBush** [comment]
Does the project use dub or simply the DMD run configuration? This sounds like something that should be looked at but would need more specific detail about how the project is setup and run. An example github project would be ideal. I'm closing this for now feel free to open further tickets for problems that don't already have open issues. There's been a few fixes since the last release so I'd like to do another soon.
