### ISSUE TITLE
Completion crashes immediately on windows....

### ISSUE THREAD

**Issue by smandy** [intellij-dlanguage/intellij-dlanguage#75]
Hi Kingsley,

Just installed plugin, really wanted the completion so compiled DCD as per instructions but get the following :-(

Cheers,
A

![image 53](https://cloud.githubusercontent.com/assets/342785/12377975/5b4df9aa-bd27-11e5-9ae4-358d002289f7.png)

**Comment by kingsleyh** [comment]
I've not seen that before - I run on OSX and Linux so have not tested on Windows. I suspect it's a bug related to running on Windows. Which version of Windows are you running and I will try to fire up a VM and test.

**Comment by kkwiatkowski** [comment]
Exactly the same error occurs on Windows 10, 64bit.
Btw, I think that @smandy uses Windows 7 (concluded by window appearance).

**Comment by kingsleyh** [comment]
Thanks - It will take me a while to get set up on windows so I can debug the issue. But I hope to provide a fix for the next release.

**Comment by smandy** [comment]
Hi Kingsley,

Yeah sorry - can confirm I'm windoze 7 :-)

Cheers,

a.

**Comment by pirocks** [comment]
@smandy I realize this issue is ancient, however try compiling the dmd build you use with ldc instead of dmd. Some people have reported issues with dmd+dcd on windows. We also have built in completion support, which is not as good as dcd, but still usable.
