### ISSUE TITLE
Nested comment highlight

### ISSUE THREAD

**Issue by trikko** [intellij-dlanguage/intellij-dlanguage#77]
Something like this

```
/*
/*
*/
```

Doesn't work, because it works as if it is nested but it is not. It greys out all the code below.

**Comment by trikko** [comment]
```
/*
//*/
```

This should close comment section too but it doesn't.

**Comment by kingsleyh** [comment]
I've struggled a bit with nested comment support. I will revisit this in the future but its on the back burner for a while until I sort out references and click through stuff

**Comment by pirocks** [comment]
`/*/*/` Is another, trickier to fix, example of this issue.

**Comment by pirocks** [comment]
Fixed.
