### ISSUE TITLE
Adding struct/interface to project creates a class for some reason

### ISSUE THREAD

**Issue by therealbluepandabear** [intellij-dlanguage/intellij-dlanguage#783]
If you create a struct like so:

![image](https://user-images.githubusercontent.com/50536495/201499688-c78cec53-dcfd-4de8-80a0-5686d2a18ec2.png)

It creates a class (instead of a struct like the user would expect):

![image](https://user-images.githubusercontent.com/50536495/201499692-4d98b31d-fc12-4343-b569-655b573a4392.png)

If you create an interface like so:

![image](https://user-images.githubusercontent.com/50536495/201499695-25646fed-4fe3-4e63-ae5c-a72b893ec2e8.png)

It creates a class (instead of an interface like the user would expect).

![image](https://user-images.githubusercontent.com/50536495/201499698-cec10987-5a06-4c72-8b9b-b08c25d928e6.png)

I cannot recreate the bug with union/enum files.

Hopefully this can get fixed.

**Comment by therealbluepandabear** [comment]
I see this hasn't gotten a reply, is this a bug or have I just misinterpreted something?

**Comment by rikkimax** [comment]
It does look like a bug, nothing to be added really.
