### ISSUE TITLE
Wrongly getting undefined symbol for string

### ISSUE THREAD

**Issue by therealbluepandabear** [intellij-dlanguage/intellij-dlanguage#784]
I have the following code:

```D
class Label : Renderable {
    string text;
    Color color;

    override Cell[] render() {
        Cell[] cells;

        int loopCount = 0;

        for (int x = 0; x < 0 + text.length; ++x) {
            cells ~= Cell(Coordinates(x, 0), text[loopCount], color);
            ++loopCount;
        }

        return cells;
    }
}
```

I am getting the following warning for no reason:

![image](https://user-images.githubusercontent.com/50536495/201500936-6a6cbe04-99f1-4989-839d-253eb7865007.png)

I think it is something to look into.

**Comment by rikkimax** [comment]
That'll be on Dscanner. Not a plugin bug.

**Comment by etienne02** [comment]
Dupplicate of https://github.com/intellij-dlanguage/intellij-dlanguage/issues/587
string is an array, and the plugin is not yet able to determine types, so it’s not able to determine that lenght is an array property

**Comment by therealbluepandabear** [comment]
k apologies
