### ISSUE TITLE
Lexer breaks in this other scenario, plus 5-10 other scenarios

### ISSUE THREAD

**Issue by therealbluepandabear** [intellij-dlanguage/intellij-dlanguage#794]
Type in the following:

```D
writeln("Hello, )
```

Then after the comma type in ' World!' like so (and only the last character should be the end of quote):

```D
writeln("Hello, World!")
```

And the highlighting is broken:

![image](https://user-images.githubusercontent.com/50536495/204181489-76059a4d-6493-4fa9-96a4-4a2180a3e316.png)

There have been another 5-10 cases where the lexer has broken as well but I can't be bothered to create issues each time.

**Comment by therealbluepandabear** [comment]
with all due respect, you guys have done a good job on this plugin... but there is something fundamentally broken with the lexer, I'm not sure what, but it's definitely very buggy, in the future when I get better with D and learn plugin development I will like to contribute to this and fix these issues and add new features that I think are important that I see in java/kotlin plugins

**Comment by therealbluepandabear** [comment]
![image](https://user-images.githubusercontent.com/50536495/204187479-d89bc8e5-cf3a-46a9-bee0-e6d5a5c6e4e0.png)

**Comment by etienne02** [comment]
All 3 issues represent the same problem. I already had it and I’m not sure of what happen here. But I can say that it’s only a highligter lexer issue, the normal lexer detect it as a string (psi-viewer will show no error). And It’s weird because the lexer is the same for syntax and highlighting. And more strange, if you remove the open character (`"` for example) and you re-add it, the error disappear

**Comment by therealbluepandabear** [comment]
well, I don't know how your software works, but there is probably a mistake somewhere in it causing this bug, good luck

**Comment by therealbluepandabear** [comment]
Any updates on this issue?

**Comment by etienne02** [comment]
No, I am able to reproduce it, but not to detect what is the issue. The lexer works correctly (if you check the psi, it’s correct) and the highlighter has the same lexer…

**Comment by therealbluepandabear** [comment]
That's annoying. Unfortunately I don't understand the codebase so I am not able to help but hopefully this issue gets solved sometime in the future, it's not urgent.

**Comment by etienne02** [comment]
I may have found something. This interface [ElementManipulator](https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/psi/ElementManipulator.java) is implemented in a lot of language for strings. They use more precisely the class [AbstractElementManipulator](https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/psi/AbstractElementManipulator.java) but I think this can help.

IMO to implement this properly, The PSI structure need to be changed to introduce one PsiElement class per Literal type (and the parser in consequence). This will help to implement a StringManipulator and also will help if we want to introduce type semantic analysis.

**Comment by rikkimax** [comment]
That is making me wonder if it might be a good idea to switch to tree-sitter for the definition of D's syntax.

Oh yeah... this is totally do-able. https://github.com/tree-sitter/tree-sitter/issues/1013

**Comment by etienne02** [comment]
Using gramnarkit, you can have a parser definition in bnf format (similar to tree-sitter). By looking at intellij-dlanguage history, the parser was in bnf format in the past but was changed to a translation of libdparse : https://github.com/intellij-dlanguage/intellij-dlanguage/issues/205
