### ISSUE TITLE
Plugin should implement some sort of intellisense 

### ISSUE THREAD

**Issue by therealbluepandabear** [intellij-dlanguage/intellij-dlanguage#798]
There is a massive disadvantage with this plugin, which is that it doesn't give you a list of suggestions for objects/methods to use (intellisense).

E.g. in kotlin when you type in anything, it shows you a list of methods to choose from (intellisense):

![image](https://user-images.githubusercontent.com/50536495/206887448-a8f1a829-b5e8-436d-ac64-9d3d886b9f91.png)

The same for enums, properties (you get the jist).

In this plugin when I type anything it gives me no suggestions, thus ruining my experience by a lot since I have to manually head to the source to see what's available.

E.g. I am using the raylib library and I want to see the colors, when I type 'Colors.' it doesn't give me suggestions:

![image](https://user-images.githubusercontent.com/50536495/206887479-2f044235-6251-4efb-8820-1da5aa237aa4.png)

I have to manually go to the file to see the list of colors, which is frustrating...

anyways it's hard to explain, but i think you get it

**Comment by rikkimax** [comment]
This is provided by DCD. You have to manually compile it and tell the plugin where to find it.

https://github.com/dlang-community/DCD

![Capture](https://user-images.githubusercontent.com/992755/206887822-a251a852-8fa1-4d15-bbf8-1a6194b3a627.PNG)

**Comment by therealbluepandabear** [comment]
ok i'll look into it , thanks
