### ISSUE TITLE
syntax highlight is different if param is var or literal

### ISSUE THREAD

**Issue by trikko** [intellij-dlanguage/intellij-dlanguage#83]
![ss](https://cloud.githubusercontent.com/assets/647157/12418181/e42f4152-bead-11e5-868b-f9329fdb2bf3.png)

**Comment by kingsleyh** [comment]
duplicate of issue #74 
I have a plan

**Comment by trikko** [comment]
I checked that issue but it seems a different case :)

**Comment by pirocks** [comment]
Syntax highlighting has changed a lot since this issue, and this is no longer relevant,
