### ISSUE TITLE
the run button of the dub tool window does not work

### ISSUE THREAD

**Issue by etienne02** [intellij-dlanguage/intellij-dlanguage#835]
**Desktop (please provide environment info):**
 - Plugin version: master

**Describe the problem**
The issue is that the runner is calling super which just threw an exception. So run will never work (but debug does)

**Please provide full details to reproduce the problem**
Create a project with dub and a main function. Click on the run icon in the side dub window. It won’t work.

**Comment by SingingBush** [comment]
The green play button in the tool window
![image](https://user-images.githubusercontent.com/870567/214451458-daa2d028-eddc-44f6-80b6-730e4565ade4.png)
