### ISSUE TITLE
support Intellij 2023

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#841]
the next major release of Intellij is likely to have breaking changes. Until it's released we should continue to target releases supporting 2022.3 - 2022.*

**Comment by SingingBush** [comment]
confirmed, we need to start doing a new build that targets 2023.1 as minimum

**Comment by etienne02** [comment]
@SingingBush I did a branch to be able to run the plugin for 2023.1 https://github.com/etienne02/intellij-dlanguage/tree/idea-2023.1

**Comment by SingingBush** [comment]
thanks, can rebase & merge that in after 1.29.4 goes out.

**Comment by SingingBush** [comment]
The intellij versions defined in `.github/workflows` will need bumping as well for the CI to pass

**Comment by SingingBush** [comment]
I've pushed a commit (https://github.com/intellij-dlanguage/intellij-dlanguage/commit/566afc6d067daebb04b97adce275548ae44d7ef5) that's a mix of your branch and PR #847. Unfortunately it seems that the more recent gradle-intellij-plugin verifyPlugin task won't work as multiple plugin descriptors are detected
