### ISSUE TITLE
Add Support for dub.sdl

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#86]
The project readme says create an issue for this, there didn't appear to be one so I am adding it.

I far prefer SDL to JSON for configuration files like this.

**Comment by cmeury** [comment]
The new DUB version 0.9.25 now supports converting between the two formats, this might be a good workaround? https://github.com/dlang/dub/issues/732

**Comment by russel** [comment]
How difficult is it to support SDL as well as JSON do people think.

**Comment by SingingBush** [comment]
We can currently import from dub.sdl but we should still add Syntax Highlighting: #46
