### ISSUE TITLE
Write new Lexer for Syntax Highlighting

### ISSUE THREAD

**Issue by kingsleyh** [intellij-dlanguage/intellij-dlanguage#87]
Currently syntax highlighting is done by re-using the main grammar lexer and then filling in the gaps using the grammar via annotation providers.

However I think a better solution would be to write a custom lexer specifically for syntax highlighting - which separates it from the grammar completely which means the highlighting will be consistent and will apply to the editor even if there are grammatical errors in the code in the editor. Currently we loose highlighting while there is a grammatical error until it's fixed.

**Comment by kingsleyh** [comment]
remove this and revert back to using main lexer for syntax highlighting

**Comment by zunkree** [comment]
Have you looked at DDT project which written on Java and I believe also have lexer?

**Comment by kingsleyh** [comment]
Yup - that's where I started almost 2 years ago

**Comment by pirocks** [comment]
There is now a separate syntax highlighting lexer. Sorry for the notification spam when closing old issues.
