### ISSUE TITLE
Add `id` for `DCDServerStatusBarWidgetFactory` registration matching its getId() value

### ISSUE THREAD

**Issue by YannCebron** [intellij-dlanguage/intellij-dlanguage#887]
https://github.com/intellij-dlanguage/intellij-dlanguage/blob/454b7e5344848452e3507a5ee08919f0bd85b028/src/main/resources/META-INF/plugin.xml#L284

required for 2023.2

**Comment by SingingBush** [comment]
Thanks for the report
