### ISSUE TITLE
dmd not autodetected on Linux (Debian)

### ISSUE THREAD

**Issue by nairboon** [intellij-dlanguage/intellij-dlanguage#909]
**Desktop (please provide environment info):**
 - OS: Debian Bookworm
 - IDE: Intellij 2023.2
 - Plugin Version: 1.32.2

**D compiler and tools (please provide version numbers):**
 - dmd: 2.100.2

**Describe the problem**
In the 'New Project' dialog, the D compiler is not auto detected.

Because `dmd` is twice in the default search path:

https://github.com/intellij-dlanguage/intellij-dlanguage/blob/3d6d2c6575a640f343b3e2d61f70c3058b0f6f4b/src/main/java/io/github/intellij/dlanguage/DlangSdkType.java#L87

https://github.com/intellij-dlanguage/intellij-dlanguage/blob/3d6d2c6575a640f343b3e2d61f70c3058b0f6f4b/src/main/java/io/github/intellij/dlanguage/DlangSdkType.java#L166-L168

**Comment by iz0eyj** [comment]
Same here, latest plugin and Intellij version.
_t is impossible to assign SDK to a new project.
