### ISSUE TITLE
add "dlang" & "dlanguage" to the plugin description/tags

### ISSUE THREAD

**Issue by nairboon** [intellij-dlanguage/intellij-dlanguage#917]
**Describe the problem**
I just wanted to install the plugin on a new intelliJ idea instance and searched for "dlang", the short name of the D language.
Turns out, neither "dlang" or "dlanguage" can find the plugin. Only "d lang"...
Maybe these words can be added in the plugin descriptions or tags?

**Screenshots**
![grafik](https://github.com/intellij-dlanguage/intellij-dlanguage/assets/88032/9f15f1e3-fed6-45f2-bf6c-5cc1bed1a46b)

**Comment by SingingBush** [comment]
Only tags defined by Jetbrains can be used to categorise plugins. However the description can be updated to use the term *dlang*
