### ISSUE TITLE
Option for disabling dfmt popups

### ISSUE THREAD

**Issue by kindlychung** [intellij-dlanguage/intellij-dlanguage#92]
This is quite distracting:

![](https://i.imgur.com/kqF2uG8.png)

**Comment by SingingBush** [comment]
is this still an issue? the code in question is in `io.github.intellij.dlanguage.actions.DFormatAction`:

```
Notifications.Bus.notify(new Notification(NOTIFICATION_GROUPID, NOTIFICATION_TITLE,
    psiFile.getName() + " formatted with DFormat.",
    NotificationType.INFORMATION), project);
```

I've not tried it as I don't use Hackerpilot's tools in my setup

**Comment by rikkimax** [comment]
In newer Intellij versions this can be hidden on a per popup basis.

So we can close this now that its been fixed by the base software.

**Comment by SingingBush** [comment]
thanks for the heads up
