### ISSUE TITLE
Intellisense based on imports

### ISSUE THREAD

**Issue by hvze** [intellij-dlanguage/intellij-dlanguage#93]
I find it frustrating that when I import something the methods from that import don't show up in autocomplete, it that a dcd thing or..?

**Comment by kingsleyh** [comment]
yeah unless its a standard library you have to go add it to the DCD list in the preferences. I've go long term plans to phase out DCD and implement intellij's own completion which will give a richer experience for intellij. But its a while off yet. But then it will fix your issue as well as provide the ability to optimize imports etc

**Comment by njasm** [comment]
would love to have this feature too.. It would help alot of newcomers to the D Lang like me.

**Comment by hvze** [comment]
@njasm The feature is in DCD, you just need to add the source of the external project to the DCD import paths.

**Comment by pirocks** [comment]
This now works with and without dcd.
