### ISSUE TITLE
Cannot set LD_LIBRARY_PATH for dub run

### ISSUE THREAD

**Issue by russel** [intellij-dlanguage/intellij-dlanguage#95]
I have set LD_LIBRARY_PATH as an environment variable in the run/debug configuration, but it appears not to be used during execution of the build executable.

**Comment by andre2007** [comment]
Will be solved with https://github.com/intellij-dlanguage/intellij-dlanguage/pull/454

**Comment by pirocks** [comment]
Merged #454.
