### ISSUE TITLE
D Tools has started to hang again

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#958]
this has been fixed previously but in current develop branch the IDE is hanging when trying to setup dub

**Comment by rikkimax** [comment]
No errors related to threading stuff?

**Comment by SingingBush** [comment]
No it just stuck completely. On https://plugins.jetbrains.com/docs/intellij/general-threading-rules.html it does state that threading changed on Intellij 2023.3 so as we're currently trying to support 2023.2 and above it's likely the code may not work in both the older and newer versions. So when fixing this, increasing the min Intellij version to 2023.3 should be done also. If I get time I can take a look today

**Comment by rikkimax** [comment]
It is odd, that if it's a EDT/BGT or read/write issue it'll show up in errors. There are a lot of diagnostics built into Intellij for this.

I'm also on 2024 and nothing seems to be wrong there.

**Comment by SingingBush** [comment]
When I hit this error I was on 2023.2 as it was whilst running from the develop branch. I've bumped the min Intellij version locally to 2023.3 and it fixed the problem. So I'm going to commit the change and count this as being resolved. Worth noting that the latest plugin release is effectively broken on 2023.2 but I don't think it's worth releasing a fix specifically for that version unless users report the problem.
