### ISSUE TITLE
default code when creating a new D source file

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#96]
when right clicking in a project folder and selecting 'New -> D File' a file is created with the following default:

```
module filename;

import std.stdio;

void main(string[] args){

}
```

this is fine for small bits of code but I think it would be more useful to have 'New -> D class', and generate something like the following:

```
module filename;

import std.stdio;

class Filename {

    this() {
    }

    ~this() {
    }

    override size_t toHash() {
        // todo
    }

    override string toString() {
        // todo: make a useful toString()
    }
}
```

also, I noticed that the module is always just the name of the file. It would be nice if it took note of the folder path so a D source file created in `source/myapp/data` would get module: `myapp.data.filename`

**Comment by pirocks** [comment]
> I noticed that the module is always just the name of the file. It would be nice if it took note of the folder path so a D source file created in source/myapp/data would get module: myapp.data.filename

I believe that if you create a module called `myapp.data.filename` the module will be created in the correct directory.

**Comment by pirocks** [comment]
Should this issue be closed?
