### ISSUE TITLE
Enum not in structure view

### ISSUE THREAD

**Issue by rikkimax** [intellij-dlanguage/intellij-dlanguage#962]
**Desktop (please provide environment info):**
 - OS: Windows 10
 - IDE: Intellij 2024.1.4
 - Plugin Version 1.34.2

**Describe the problem**

This is the last enum in the screenshot:

```d
/// What should happend when an assertion fails
enum CHECKACTION : ubyte
{
    D,            /// call D assert on failure
    C,            /// call C assert on failure
    halt,         /// cause program halt on failure
    context,      /// call D assert with the error context on failure
}
```

It can be jumped to.

**Screenshots**

![Capture](https://github.com/intellij-dlanguage/intellij-dlanguage/assets/992755/6276470d-3f8e-41c6-9b83-b8bae1c45c73)

**Comment by etienne02** [comment]
I updated the previous PR to also fix this one (and globally improve the view)

**Comment by rikkimax** [comment]
Awesome!
