### ISSUE TITLE
check PATH for dmd

### ISSUE THREAD

**Issue by SingingBush** [intellij-dlanguage/intellij-dlanguage#97]
I just used the File menu to create a new project with dub support. When getting to the Project SDK tab I had to manually select 'Configure...' and choose `/usr/bin/dmd` for the plugin to see that I have DMD v2.071. Please just default to the version of dmd that is on the PATH with an option to override.

Also, it would be good if the next page for choosing the dub binary had the same layout and confirmation of version number when found.

**Comment by SingingBush** [comment]
when running the gradle branch with `./gradlew runIdea` and opening existing D project (Mac OSX) I found there is a slight issue with the way that the plugin locates my D compiler. I install dmd using homebrew and doing `which dmd` shows that the path is `/usr/local/bin/dmd` however when setting _Project SDK_ in Intellij it defaults to `/usr/local/opt/dmd`. 

I think it would be better for it to use the symlink but if it is going to use the path to opt then it should use the full path to executable: `/usr/local/opt/dmd/bin/dmd`

**Comment by SingingBush** [comment]
this was pretty much sorted in #147 but will keep open for now as want to double check. The locations that should be searched for OSX, Linux and Windows.

**Comment by pirocks** [comment]
I think a commit I pushed a while ago provided the correct location for windows:
https://github.com/intellij-dlanguage/intellij-dlanguage/blob/develop/src/main/java/net/masterthought/dlanguage/utils/ExecUtil.java#L137
Is this still an issue/should I double check on other machines?

**Comment by SingingBush** [comment]
from what I remember it was all ok but having another person look at it is a good idea.

**Comment by pirocks** [comment]
Everything dmd executable finding related seems to work now.
